# Generated by Django 6.0 on 2025-12-06 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesel', models.CharField(max_length=11)),
                ('nr_dowodu', models.CharField(max_length=11)),
                ('imie', models.CharField(max_length=255)),
                ('nazwisko', models.CharField(max_length=255)),
                ('data_urodzenia', models.DateField()),
                ('miejsce_urodzenia', models.CharField(max_length=255)),
                ('numer_telefonu', models.CharField(blank=True, max_length=11, null=True)),
                ('data_wypadku', models.DateField()),
                ('godzina_wypadku', models.TimeField()),
                ('miejsce_wypadku', models.CharField(max_length=255)),
                ('planowana_godzina_rozpoczecia_pracy', models.TimeField()),
                ('planowana_godzina_zakonczenia_pracy', models.TimeField()),
                ('rodzaj_urazow', models.TextField()),
                ('szczegoly_okolicznosci', models.TextField()),
                ('czy_udzielona_pomoc', models.BooleanField(default=False)),
                ('miejsce_udzielenia_pomocy', models.CharField(blank=True, max_length=255, null=True)),
                ('organ_postepowania', models.CharField(blank=True, max_length=255, null=True)),
                ('czy_wypadek_podczas_uzywania_maszyny', models.BooleanField(default=False)),
                ('opis_maszyn', models.TextField(blank=True, null=True)),
                ('czy_maszyna_posiada_atest', models.BooleanField(blank=True, default=False, null=True)),
                ('czy_maszyna_w_ewidencji', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=255)),
                ('nazwisko', models.CharField(max_length=255)),
                ('ulica', models.CharField(max_length=255)),
                ('nr_domu', models.CharField(max_length=11)),
                ('nr_lokalu', models.CharField(blank=True, max_length=11, null=True)),
                ('miejscowosc', models.CharField(max_length=255)),
                ('kod_pocztowy', models.CharField(max_length=6)),
                ('nazwa_panstwa', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.document')),
            ],
        ),
    ]
