# Generated by Django 6.0 on 2025-12-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='data_urodzenia_zglaszajacego',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='imie_zglaszajacego',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='kod_pocztowy',
            field=models.CharField(default=' ', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='kod_pocztowy_dzialalnosci',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='kod_pocztowy_korespondencji',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='kod_pocztowy_korespondencji_zglaszajacego',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='kod_pocztowy_opieki',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='kod_pocztowy_ostatniego_zamieszkania',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='kod_pocztowy_zglaszajacego',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='kod_pocztowy_zglaszajacego_ostatniego_zamieszkania',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='miejscowosc',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='miejscowosc_dzialalnosci',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='miejscowosc_korespondencji',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='miejscowosc_korespondencji_zglaszajacego',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='miejscowosc_opieki',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='miejscowosc_ostatniego_zamieszkania',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='miejscowosc_zglaszajacego',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='miejscowosc_zglaszajacego_ostatniego_zamieszkania',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='nazwa_panstwa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='nazwa_panstwa_korespondencji',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='nazwa_panstwa_korespondencji_zglaszajacego',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='nazwisko_zglaszajacego',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='nr_domu',
            field=models.CharField(default=' ', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='nr_domu_dzialalnosci',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='nr_domu_korespondencji',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='nr_domu_korespondencji_zglaszajacego',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='nr_domu_opieki',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='nr_domu_ostatniego_zamieszkania',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='nr_domu_zglaszajacego',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='nr_domu_zglaszajacego_ostatniego_zamieszkania',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='nr_dowodu_zglaszajacego',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='nr_lokalu',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='nr_lokalu_dzialalnosci',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='nr_lokalu_korespondencji',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='nr_lokalu_korespondencji_zglaszajacego',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='nr_lokalu_opieki',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='nr_lokalu_ostatniego_zamieszkania',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='nr_lokalu_zglaszajacego',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='nr_lokalu_zglaszajacego_ostatniego_zamieszkania',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='nr_telefonu_dzialalnosci',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='nr_telefonu_opieki',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='nr_telefonu_zglaszajacego',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='pesel_zglaszajacego',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='typ_korespondencji',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='typ_korespondencji_zglaszajacego',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='ulica',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='ulica_dzialalnosci',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='ulica_korespondencji',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='ulica_korespondencji_zglaszajacego',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='ulica_opieki',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='ulica_ostatniego_zamieszkania',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='ulica_zglaszajacego',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='ulica_zglaszajacego_ostatniego_zamieszkania',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
