# Generated by Django 4.2.27 on 2025-12-07 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_document_data_urodzenia_zglaszajacego_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='witness',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnesses', to='api.document'),
        ),
    ]
