export interface Witness {
  id?: number;
  imie: string;
  nazwisko: string;
  ulica: string;
  nr_domu: string;
  nr_lokalu: string | null;
  miejscowosc: string;
  kod_pocztowy: string;
  nazwa_panstwa: string | null;
  document: number | Document;
}

export interface Document {
  id?: number;
  pesel: string;
  nr_dowodu: string;
  imie: string;
  nazwisko: string;
  data_urodzenia: string;
  miejsce_urodzenia: string;
  numer_telefonu: string | null;
  ulica: string;
  nr_domu: string;
  nr_lokalu: string | null;
  miejscowosc: string;
  kod_pocztowy: string;
  nazwa_panstwa: string | null;
  ulica_ostatniego_zamieszkania: string | null;
  nr_domu_ostatniego_zamieszkania: string | null;
  nr_lokalu_ostatniego_zamieszkania: string | null;
  miejscowosc_ostatniego_zamieszkania: string | null;
  kod_pocztowy_ostatniego_zamieszkania: string | null;
  typ_korespondencji: string | null;
  ulica_korespondencji: string | null;
  nr_domu_korespondencji: string | null;
  nr_lokalu_korespondencji: string | null;
  miejscowosc_korespondencji: string | null;
  kod_pocztowy_korespondencji: string | null;
  nazwa_panstwa_korespondencji: string | null;
  ulica_dzialalnosci: string | null;
  nr_domu_dzialalnosci: string | null;
  nr_lokalu_dzialalnosci: string | null;
  miejscowosc_dzialalnosci: string | null;
  kod_pocztowy_dzialalnosci: string | null;
  nr_telefonu_dzialalnosci: string | null;
  ulica_opieki: string | null;
  nr_domu_opieki: string | null;
  nr_lokalu_opieki: string | null;
  miejscowosc_opieki: string | null;
  kod_pocztowy_opieki: string | null;
  nr_telefonu_opieki: string | null;
  imie_zglaszajacego: string | null;
  nazwisko_zglaszajacego: string | null;
  pesel_zglaszajacego: string | null;
  nr_dowodu_zglaszajacego: string | null;
  data_urodzenia_zglaszajacego: string | null;
  nr_telefonu_zglaszajacego: string | null;
  ulica_zglaszajacego: string | null;
  nr_domu_zglaszajacego: string | null;
  nr_lokalu_zglaszajacego: string | null;
  miejscowosc_zglaszajacego: string | null;
  kod_pocztowy_zglaszajacego: string | null;
  ulica_zglaszajacego_ostatniego_zamieszkania: string | null;
  nr_domu_zglaszajacego_ostatniego_zamieszkania: string | null;
  nr_lokalu_zglaszajacego_ostatniego_zamieszkania: string | null;
  miejscowosc_zglaszajacego_ostatniego_zamieszkania: string | null;
  kod_pocztowy_zglaszajacego_ostatniego_zamieszkania: string | null;
  typ_korespondencji_zglaszajacego: string | null;
  ulica_korespondencji_zglaszajacego: string | null;
  nr_domu_korespondencji_zglaszajacego: string | null;
  nr_lokalu_korespondencji_zglaszajacego: string | null;
  miejscowosc_korespondencji_zglaszajacego: string | null;
  kod_pocztowy_korespondencji_zglaszajacego: string | null;
  nazwa_panstwa_korespondencji_zglaszajacego: string | null;
  data_wypadku: string;
  godzina_wypadku: string;
  miejsce_wypadku: string;
  planowana_godzina_rozpoczecia_pracy: string;
  planowana_godzina_zakonczenia_pracy: string;
  rodzaj_urazow: string;
  szczegoly_okolicznosci: string;
  czy_udzielona_pomoc: boolean;
  miejsce_udzielenia_pomocy: string | null;
  organ_postepowania: string | null;
  czy_wypadek_podczas_uzywania_maszyny: boolean;
  opis_maszyn: string | null;
  czy_maszyna_posiada_atest: boolean | null;
  czy_maszyna_w_ewidencji: boolean | null;
  witnesses?: Witness[];
}
