import type { Document } from "@/types/document";

export const defaultDocumentData: Document = {
  id: undefined,
  pesel: "00000000000",
  nr_dowodu: "AAA000000",
  imie: "Nieznane",
  nazwisko: "Nieznane",
  data_urodzenia: "1990-01-01",
  miejsce_urodzenia: "Nieznane",
  numer_telefonu: null,
  ulica: "Brak danych",
  nr_domu: "0",
  nr_lokalu: null,
  miejscowosc: "Brak danych",
  kod_pocztowy: "00-000",
  nazwa_panstwa: "Polska",
  ulica_ostatniego_zamieszkania: null,
  nr_domu_ostatniego_zamieszkania: null,
  nr_lokalu_ostatniego_zamieszkania: null,
  miejscowosc_ostatniego_zamieszkania: null,
  kod_pocztowy_ostatniego_zamieszkania: null,
  typ_korespondencji: null,
  ulica_korespondencji: null,
  nr_domu_korespondencji: null,
  nr_lokalu_korespondencji: null,
  miejscowosc_korespondencji: null,
  kod_pocztowy_korespondencji: null,
  nazwa_panstwa_korespondencji: null,
  ulica_dzialalnosci: null,
  nr_domu_dzialalnosci: null,
  nr_lokalu_dzialalnosci: null,
  miejscowosc_dzialalnosci: null,
  kod_pocztowy_dzialalnosci: null,
  nr_telefonu_dzialalnosci: null,
  ulica_opieki: null,
  nr_domu_opieki: null,
  nr_lokalu_opieki: null,
  miejscowosc_opieki: null,
  kod_pocztowy_opieki: null,
  nr_telefonu_opieki: null,
  imie_zglaszajacego: "Nieznane",
  nazwisko_zglaszajacego: "Nieznane",
  pesel_zglaszajacego: null,
  nr_dowodu_zglaszajacego: null,
  data_urodzenia_zglaszajacego: null,
  nr_telefonu_zglaszajacego: null,
  ulica_zglaszajacego: null,
  nr_domu_zglaszajacego: null,
  nr_lokalu_zglaszajacego: null,
  miejscowosc_zglaszajacego: null,
  kod_pocztowy_zglaszajacego: null,
  ulica_zglaszajacego_ostatniego_zamieszkania: null,
  nr_domu_zglaszajacego_ostatniego_zamieszkania: null,
  nr_lokalu_zglaszajacego_ostatniego_zamieszkania: null,
  miejscowosc_zglaszajacego_ostatniego_zamieszkania: null,
  kod_pocztowy_zglaszajacego_ostatniego_zamieszkania: null,
  typ_korespondencji_zglaszajacego: null,
  ulica_korespondencji_zglaszajacego: null,
  nr_domu_korespondencji_zglaszajacego: null,
  nr_lokalu_korespondencji_zglaszajacego: null,
  miejscowosc_korespondencji_zglaszajacego: null,
  kod_pocztowy_korespondencji_zglaszajacego: null,
  nazwa_panstwa_korespondencji_zglaszajacego: null,
  data_wypadku: "2025-01-01",
  godzina_wypadku: "08:00",
  miejsce_wypadku: "Brak danych",
  planowana_godzina_rozpoczecia_pracy: "08:00",
  planowana_godzina_zakonczenia_pracy: "16:00",
  rodzaj_urazow: "Brak danych",
  szczegoly_okolicznosci: "Brak danych",
  czy_udzielona_pomoc: false,
  miejsce_udzielenia_pomocy: null,
  organ_postepowania: null,
  czy_wypadek_podczas_uzywania_maszyny: false,
  opis_maszyn: null,
  czy_maszyna_posiada_atest: null,
  czy_maszyna_w_ewidencji: null,
  witnesses: [],
};

const createDocument = (overrides: Partial<Document>): Document => ({
  ...defaultDocumentData,
  ...overrides,
});

export const mockDocuments: Document[] = [
  createDocument({
    id: 1,
    pesel: "90010112345",
    nr_dowodu: "AAR123456",
    imie: "Jan",
    nazwisko: "Kowalski",
    data_urodzenia: "1990-01-01",
    miejsce_urodzenia: "Warszawa",
    numer_telefonu: "+48 123 456 789",
    ulica: "Prosta",
    nr_domu: "12",
    nr_lokalu: "4",
    miejscowosc: "Warszawa",
    kod_pocztowy: "00-950",
    data_wypadku: "2025-11-26",
    godzina_wypadku: "14:35",
    miejsce_wypadku: "Budowa centrum logistycznego, Mokotów",
    planowana_godzina_rozpoczecia_pracy: "07:00",
    planowana_godzina_zakonczenia_pracy: "15:00",
    rodzaj_urazow: "Złamanie kości przedramienia",
    szczegoly_okolicznosci:
      "Poślizgnięcie na oblodzonej powierzchni rusztowania podczas montażu stalowych belek. Poszkodowany spadł na platformę zabezpieczającą i doznał urazu ręki.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "SOR Szpitala na Wołoskiej",
    organ_postepowania: "PIP Warszawa",
    czy_wypadek_podczas_uzywania_maszyny: true,
    opis_maszyn: "Elektryczne rusztowanie przestawne",
    czy_maszyna_posiada_atest: true,
    czy_maszyna_w_ewidencji: true,
    imie_zglaszajacego: "Jan",
    nazwisko_zglaszajacego: "Kowalski",
    pesel_zglaszajacego: "90010112345",
    nr_dowodu_zglaszajacego: "AAR123456",
    nr_telefonu_zglaszajacego: "+48 123 456 789",
    ulica_zglaszajacego: "Prosta",
    nr_domu_zglaszajacego: "12",
    miejscowosc_zglaszajacego: "Warszawa",
    kod_pocztowy_zglaszajacego: "00-950",
    witnesses: [
      {
        imie: "Piotr",
        nazwisko: "Lis",
        ulica: "Płocka",
        nr_domu: "8",
        nr_lokalu: "2",
        miejscowosc: "Warszawa",
        kod_pocztowy: "01-231",
        nazwa_panstwa: "Polska",
        document: 1,
      },
    ],
  }),
  createDocument({
    id: 2,
    pesel: "87050567890",
    nr_dowodu: "BTR987654",
    imie: "Marek",
    nazwisko: "Fronczak",
    data_urodzenia: "1987-05-05",
    miejsce_urodzenia: "Łódź",
    numer_telefonu: "+48 600 200 155",
    ulica: "Łąkowa",
    nr_domu: "7",
    nr_lokalu: null,
    miejscowosc: "Łódź",
    kod_pocztowy: "90-562",
    data_wypadku: "2025-11-25",
    godzina_wypadku: "11:10",
    miejsce_wypadku: "Hala pras hydraulicznych w zakładzie produkcyjnym",
    planowana_godzina_rozpoczecia_pracy: "06:00",
    planowana_godzina_zakonczenia_pracy: "14:00",
    rodzaj_urazow: "Zmiażdżenie dwóch palców dłoni",
    szczegoly_okolicznosci: "Pracownik prowadził regulację czujników krańcowych. Doszło do awarii zaworu i stół opadł, przygniatając dłoń.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "Szpital im. Kopernika w Łodzi",
    organ_postepowania: "PIP Łódź",
    czy_wypadek_podczas_uzywania_maszyny: true,
    opis_maszyn: "Prasa hydrauliczna 350 ton",
    czy_maszyna_posiada_atest: true,
    czy_maszyna_w_ewidencji: true,
    imie_zglaszajacego: "Anna",
    nazwisko_zglaszajacego: "Nowak",
    nr_telefonu_zglaszajacego: "+48 987 654 321",
    ulica_zglaszajacego: "Sienkiewicza",
    nr_domu_zglaszajacego: "20",
    miejscowosc_zglaszajacego: "Łódź",
    kod_pocztowy_zglaszajacego: "90-113",
  }),
  createDocument({
    id: 3,
    pesel: "78032378901",
    nr_dowodu: "CCR556677",
    imie: "Ewelina",
    nazwisko: "Gajda",
    data_urodzenia: "1978-03-23",
    miejsce_urodzenia: "Poznań",
    numer_telefonu: "+48 501 222 333",
    ulica: "Wiosny Ludów",
    nr_domu: "3",
    nr_lokalu: null,
    miejscowosc: "Poznań",
    kod_pocztowy: "61-831",
    data_wypadku: "2025-12-02",
    godzina_wypadku: "07:50",
    miejsce_wypadku: "Linia rozlewnicza środków chemicznych",
    planowana_godzina_rozpoczecia_pracy: "06:00",
    planowana_godzina_zakonczenia_pracy: "14:00",
    rodzaj_urazow: "Oparzenia chemiczne dłoni",
    szczegoly_okolicznosci: "Rozłączenie złącza przy pracy rękawicą ochronną. Środek o pH 13 zalał rękawicę i spowodował oparzenia.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "Szpital im. Raszei w Poznaniu",
    organ_postepowania: "PIP Poznań",
    czy_wypadek_podczas_uzywania_maszyny: false,
    opis_maszyn: null,
    czy_maszyna_posiada_atest: null,
    czy_maszyna_w_ewidencji: null,
  }),
  createDocument({
    id: 4,
    pesel: "75081234567",
    nr_dowodu: "DDR445566",
    imie: "Piotr",
    nazwisko: "Lewandowski",
    data_urodzenia: "1975-08-12",
    miejsce_urodzenia: "Gdańsk",
    numer_telefonu: "+48 555 123 456",
    ulica: "Długa",
    nr_domu: "5",
    nr_lokalu: "7",
    miejscowosc: "Gdańsk",
    kod_pocztowy: "80-827",
    data_wypadku: "2025-11-23",
    godzina_wypadku: "09:40",
    miejsce_wypadku: "Archiwum akt pracowniczych",
    planowana_godzina_rozpoczecia_pracy: "08:00",
    planowana_godzina_zakonczenia_pracy: "16:00",
    rodzaj_urazow: "Skręcenie stawu skokowego",
    szczegoly_okolicznosci: "Do potknięcia doszło przy ciasnym przejściu. Na podłodze znajdował się przewód przedłużacza.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "Lekarz zakładowy",
    organ_postepowania: null,
    czy_wypadek_podczas_uzywania_maszyny: false,
  }),
  createDocument({
    id: 5,
    pesel: "92071506789",
    nr_dowodu: "EER778899",
    imie: "Kamil",
    nazwisko: "Król",
    data_urodzenia: "1992-07-15",
    miejsce_urodzenia: "Radom",
    numer_telefonu: "+48 600 100 200",
    ulica: "Fabryczna",
    nr_domu: "18",
    nr_lokalu: null,
    miejscowosc: "Radom",
    kod_pocztowy: "26-600",
    data_wypadku: "2025-12-03",
    godzina_wypadku: "05:40",
    miejsce_wypadku: "Strefa przyjęć towaru w magazynie",
    planowana_godzina_rozpoczecia_pracy: "06:00",
    planowana_godzina_zakonczenia_pracy: "14:00",
    rodzaj_urazow: "Stłuczenie biodra",
    szczegoly_okolicznosci: "Rozlane zostały płyny techniczne z uszkodzonego pojemnika. Strefa nie była oznakowana.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "SOR Radom",
    organ_postepowania: null,
    czy_wypadek_podczas_uzywania_maszyny: false,
  }),
];
