import type { Document } from "@/types/document";

export const defaultDocumentData: Document = {
  id: undefined,
  pesel: "00000000000",
  nr_dowodu: "AAA000000",
  imie: "Nieznane",
  nazwisko: "Nieznane",
  data_urodzenia: "1990-01-01",
  miejsce_urodzenia: "Nieznane",
  numer_telefonu: null,
  ulica: "Brak danych",
  nr_domu: "0",
  nr_lokalu: null,
  miejscowosc: "Brak danych",
  kod_pocztowy: "00-000",
  nazwa_panstwa: "Polska",
  ulica_ostatniego_zamieszkania: null,
  nr_domu_ostatniego_zamieszkania: null,
  nr_lokalu_ostatniego_zamieszkania: null,
  miejscowosc_ostatniego_zamieszkania: null,
  kod_pocztowy_ostatniego_zamieszkania: null,
  typ_korespondencji: null,
  ulica_korespondencji: null,
  nr_domu_korespondencji: null,
  nr_lokalu_korespondencji: null,
  miejscowosc_korespondencji: null,
  kod_pocztowy_korespondencji: null,
  nazwa_panstwa_korespondencji: null,
  ulica_dzialalnosci: null,
  nr_domu_dzialalnosci: null,
  nr_lokalu_dzialalnosci: null,
  miejscowosc_dzialalnosci: null,
  kod_pocztowy_dzialalnosci: null,
  nr_telefonu_dzialalnosci: null,
  ulica_opieki: null,
  nr_domu_opieki: null,
  nr_lokalu_opieki: null,
  miejscowosc_opieki: null,
  kod_pocztowy_opieki: null,
  nr_telefonu_opieki: null,
  imie_zglaszajacego: "Nieznane",
  nazwisko_zglaszajacego: "Nieznane",
  pesel_zglaszajacego: null,
  nr_dowodu_zglaszajacego: null,
  data_urodzenia_zglaszajacego: null,
  nr_telefonu_zglaszajacego: null,
  ulica_zglaszajacego: null,
  nr_domu_zglaszajacego: null,
  nr_lokalu_zglaszajacego: null,
  miejscowosc_zglaszajacego: null,
  kod_pocztowy_zglaszajacego: null,
  ulica_zglaszajacego_ostatniego_zamieszkania: null,
  nr_domu_zglaszajacego_ostatniego_zamieszkania: null,
  nr_lokalu_zglaszajacego_ostatniego_zamieszkania: null,
  miejscowosc_zglaszajacego_ostatniego_zamieszkania: null,
  kod_pocztowy_zglaszajacego_ostatniego_zamieszkania: null,
  typ_korespondencji_zglaszajacego: null,
  ulica_korespondencji_zglaszajacego: null,
  nr_domu_korespondencji_zglaszajacego: null,
  nr_lokalu_korespondencji_zglaszajacego: null,
  miejscowosc_korespondencji_zglaszajacego: null,
  kod_pocztowy_korespondencji_zglaszajacego: null,
  nazwa_panstwa_korespondencji_zglaszajacego: null,
  data_wypadku: "2025-01-01",
  godzina_wypadku: "08:00",
  miejsce_wypadku: "Brak danych",
  planowana_godzina_rozpoczecia_pracy: "08:00",
  planowana_godzina_zakonczenia_pracy: "16:00",
  rodzaj_urazow: "Brak danych",
  szczegoly_okolicznosci: "Brak danych",
  czy_udzielona_pomoc: false,
  miejsce_udzielenia_pomocy: null,
  organ_postepowania: null,
  czy_wypadek_podczas_uzywania_maszyny: false,
  opis_maszyn: null,
  czy_maszyna_posiada_atest: null,
  czy_maszyna_w_ewidencji: null,
  witnesses: [],
};

const createDocument = (overrides: Partial<Document>): Document => ({
  ...defaultDocumentData,
  ...overrides,
});

export const mockDocuments: Document[] = [
  createDocument({
    id: 1,
    pesel: "90010112345",
    nr_dowodu: "AAR123456",
    imie: "Jan",
    nazwisko: "Kowalski",
    data_urodzenia: "1990-01-01",
    miejsce_urodzenia: "Warszawa",
    numer_telefonu: "+48 123 456 789",
    ulica: "Prosta",
    nr_domu: "12",
    nr_lokalu: "4",
    miejscowosc: "Warszawa",
    kod_pocztowy: "00-950",
    data_wypadku: "2025-11-26",
    godzina_wypadku: "14:35",
    miejsce_wypadku: "Budowa centrum logistycznego, Mokotów",
    planowana_godzina_rozpoczecia_pracy: "07:00",
    planowana_godzina_zakonczenia_pracy: "15:00",
    rodzaj_urazow: "Złamanie kości przedramienia",
    szczegoly_okolicznosci:
      "Poślizgnięcie na oblodzonej powierzchni rusztowania podczas montażu stalowych belek. Poszkodowany spadł na platformę zabezpieczającą i doznał urazu ręki.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "SOR Szpitala na Wołoskiej",
    organ_postepowania: "PIP Warszawa",
    czy_wypadek_podczas_uzywania_maszyny: true,
    opis_maszyn: "Elektryczne rusztowanie przestawne",
    czy_maszyna_posiada_atest: true,
    czy_maszyna_w_ewidencji: true,
    imie_zglaszajacego: "Jan",
    nazwisko_zglaszajacego: "Kowalski",
    pesel_zglaszajacego: "90010112345",
    nr_dowodu_zglaszajacego: "AAR123456",
    nr_telefonu_zglaszajacego: "+48 123 456 789",
    ulica_zglaszajacego: "Prosta",
    nr_domu_zglaszajacego: "12",
    miejscowosc_zglaszajacego: "Warszawa",
    kod_pocztowy_zglaszajacego: "00-950",
    witnesses: [
      {
        imie: "Piotr",
        nazwisko: "Lis",
        numer_telefonu: "+48 888 111 222",
        adres_email: "piotr.lis@example.com",
        ulica: "Płocka",
        nr_domu: "8",
        nr_lokalu: "2",
        miejscowosc: "Warszawa",
        kod_pocztowy: "01-231",
        nazwa_panstwa: "Polska",
        document: 1,
      },
    ],
  }),
  createDocument({
    id: 2,
    pesel: "87050567890",
    nr_dowodu: "BTR987654",
    imie: "Marek",
    nazwisko: "Fronczak",
    data_urodzenia: "1987-05-05",
    miejsce_urodzenia: "Łódź",
    numer_telefonu: "+48 600 200 155",
    ulica: "Łąkowa",
    nr_domu: "7",
    nr_lokalu: null,
    miejscowosc: "Łódź",
    kod_pocztowy: "90-562",
    data_wypadku: "2025-11-25",
    godzina_wypadku: "11:10",
    miejsce_wypadku: "Hala pras hydraulicznych w zakładzie produkcyjnym",
    planowana_godzina_rozpoczecia_pracy: "06:00",
    planowana_godzina_zakonczenia_pracy: "14:00",
    rodzaj_urazow: "Zmiażdżenie dwóch palców dłoni",
    szczegoly_okolicznosci: "Pracownik prowadził regulację czujników krańcowych. Doszło do awarii zaworu i stół opadł, przygniatając dłoń.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "Szpital im. Kopernika w Łodzi",
    organ_postepowania: "PIP Łódź",
    czy_wypadek_podczas_uzywania_maszyny: true,
    opis_maszyn: "Prasa hydrauliczna 350 ton",
    czy_maszyna_posiada_atest: true,
    czy_maszyna_w_ewidencji: true,
    imie_zglaszajacego: "Anna",
    nazwisko_zglaszajacego: "Nowak",
    nr_telefonu_zglaszajacego: "+48 987 654 321",
    ulica_zglaszajacego: "Sienkiewicza",
    nr_domu_zglaszajacego: "20",
    miejscowosc_zglaszajacego: "Łódź",
    kod_pocztowy_zglaszajacego: "90-113",
  }),
  createDocument({
    id: 3,
    pesel: "78032378901",
    nr_dowodu: "CCR556677",
    imie: "Ewelina",
    nazwisko: "Gajda",
    data_urodzenia: "1978-03-23",
    miejsce_urodzenia: "Poznań",
    numer_telefonu: "+48 501 222 333",
    ulica: "Wiosny Ludów",
    nr_domu: "3",
    nr_lokalu: null,
    miejscowosc: "Poznań",
    kod_pocztowy: "61-831",
    data_wypadku: "2025-12-02",
    godzina_wypadku: "07:50",
    miejsce_wypadku: "Linia rozlewnicza środków chemicznych",
    planowana_godzina_rozpoczecia_pracy: "06:00",
    planowana_godzina_zakonczenia_pracy: "14:00",
    rodzaj_urazow: "Oparzenia chemiczne dłoni",
    szczegoly_okolicznosci: "Rozłączenie złącza przy pracy rękawicą ochronną. Środek o pH 13 zalał rękawicę i spowodował oparzenia.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "Szpital im. Raszei w Poznaniu",
    organ_postepowania: "PIP Poznań",
    czy_wypadek_podczas_uzywania_maszyny: false,
    opis_maszyn: null,
    czy_maszyna_posiada_atest: null,
    czy_maszyna_w_ewidencji: null,
  }),
  createDocument({
    id: 4,
    pesel: "75081234567",
    nr_dowodu: "DDR445566",
    imie: "Piotr",
    nazwisko: "Lewandowski",
    data_urodzenia: "1975-08-12",
    miejsce_urodzenia: "Gdańsk",
    numer_telefonu: "+48 555 123 456",
    ulica: "Długa",
    nr_domu: "5",
    nr_lokalu: "7",
    miejscowosc: "Gdańsk",
    kod_pocztowy: "80-827",
    data_wypadku: "2025-11-23",
    godzina_wypadku: "09:40",
    miejsce_wypadku: "Archiwum akt pracowniczych",
    planowana_godzina_rozpoczecia_pracy: "08:00",
    planowana_godzina_zakonczenia_pracy: "16:00",
    rodzaj_urazow: "Skręcenie stawu skokowego",
    szczegoly_okolicznosci: "Do potknięcia doszło przy ciasnym przejściu. Na podłodze znajdował się przewód przedłużacza.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "Lekarz zakładowy",
    organ_postepowania: null,
    czy_wypadek_podczas_uzywania_maszyny: false,
  }),
  createDocument({
    id: 5,
    pesel: "92071506789",
    nr_dowodu: "EER778899",
    imie: "Kamil",
    nazwisko: "Król",
    data_urodzenia: "1992-07-15",
    miejsce_urodzenia: "Radom",
    numer_telefonu: "+48 600 100 200",
    ulica: "Fabryczna",
    nr_domu: "18",
    nr_lokalu: null,
    miejscowosc: "Radom",
    kod_pocztowy: "26-600",
    data_wypadku: "2025-12-03",
    godzina_wypadku: "05:40",
    miejsce_wypadku: "Strefa przyjęć towaru w magazynie",
    planowana_godzina_rozpoczecia_pracy: "06:00",
    planowana_godzina_zakonczenia_pracy: "14:00",
    rodzaj_urazow: "Stłuczenie biodra",
    szczegoly_okolicznosci: "Rozlane zostały płyny techniczne z uszkodzonego pojemnika. Strefa nie była oznakowana.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "SOR Radom",
    organ_postepowania: null,
    czy_wypadek_podczas_uzywania_maszyny: false,
  }),
  createDocument({
    id: 6,
    pesel: "93021445678",
    nr_dowodu: "FFR445512",
    imie: "Sylwia",
    nazwisko: "Wojcik",
    data_urodzenia: "1993-02-14",
    miejsce_urodzenia: "Kraków",
    numer_telefonu: "+48 511 222 410",
    ulica: "Dobra",
    nr_domu: "14",
    nr_lokalu: "6",
    miejscowosc: "Kraków",
    kod_pocztowy: "30-527",
    data_wypadku: "2025-11-28",
    godzina_wypadku: "10:20",
    miejsce_wypadku: "Pracownia projektowa biura architektonicznego",
    planowana_godzina_rozpoczecia_pracy: "08:00",
    planowana_godzina_zakonczenia_pracy: "16:00",
    rodzaj_urazow: "Oparzenie dłoni gorącą kawą",
    szczegoly_okolicznosci:
      "Czajnik o uszkodzonym kablu przewrócił się przy próbie podniesienia. Gorąca woda oblała dłoń pracownicy.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "Gabinet lekarza medycyny pracy",
    organ_postepowania: null,
    czy_wypadek_podczas_uzywania_maszyny: false,
    imie_zglaszajacego: "Sylwia",
    nazwisko_zglaszajacego: "Wojcik",
    nr_telefonu_zglaszajacego: "+48 511 222 410",
  }),
  createDocument({
    id: 7,
    pesel: "82090998765",
    nr_dowodu: "GGR334455",
    imie: "Radosław",
    nazwisko: "Milewski",
    data_urodzenia: "1982-09-09",
    miejsce_urodzenia: "Toruń",
    numer_telefonu: "+48 780 222 119",
    ulica: "Kościuszki",
    nr_domu: "21",
    nr_lokalu: null,
    miejscowosc: "Toruń",
    kod_pocztowy: "87-100",
    data_wypadku: "2025-11-29",
    godzina_wypadku: "22:15",
    miejsce_wypadku: "Linia pakowania pieczywa nocnej zmiany",
    planowana_godzina_rozpoczecia_pracy: "20:00",
    planowana_godzina_zakonczenia_pracy: "04:00",
    rodzaj_urazow: "Poważne skaleczenie dłoni",
    szczegoly_okolicznosci:
      "Nóż taśmowy zaciął rękaw ochronny podczas wymiany rolek. Pracownik nie odłączył zasilania mimo procedury.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "Szpital Miejski w Toruniu",
    organ_postepowania: "PIP Bydgoszcz",
    czy_wypadek_podczas_uzywania_maszyny: true,
    opis_maszyn: "Automatyczna krajalnica do chleba",
    czy_maszyna_posiada_atest: true,
    czy_maszyna_w_ewidencji: true,
    imie_zglaszajacego: "Ewa",
    nazwisko_zglaszajacego: "Piekarczyk",
    nr_telefonu_zglaszajacego: "+48 780 333 221",
    witnesses: [
      {
        imie: "Michał",
        nazwisko: "Ostrowski",
        ulica: "Szeroka",
        nr_domu: "18",
        nr_lokalu: "1",
        miejscowosc: "Toruń",
        kod_pocztowy: "87-100",
        nazwa_panstwa: "Polska",
        document: 7,
      },
    ],
  }),
  createDocument({
    id: 8,
    pesel: "95050143210",
    nr_dowodu: "HHR998877",
    imie: "Natalia",
    nazwisko: "Baran",
    data_urodzenia: "1995-05-01",
    miejsce_urodzenia: "Rzeszów",
    numer_telefonu: "+48 505 303 202",
    ulica: "Kwiatowa",
    nr_domu: "2",
    nr_lokalu: "5",
    miejscowosc: "Rzeszów",
    kod_pocztowy: "35-111",
    data_wypadku: "2025-12-01",
    godzina_wypadku: "16:45",
    miejsce_wypadku: "Magazyn wyrobów farmaceutycznych",
    planowana_godzina_rozpoczecia_pracy: "09:00",
    planowana_godzina_zakonczenia_pracy: "17:00",
    rodzaj_urazow: "Skręcenie nadgarstka",
    szczegoly_okolicznosci:
      "Podczas odkładania pojemnika z fiolkami operator podestów ruszył bez sygnału dźwiękowego, co spowodowało uderzenie w regał.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "Kliniczny Szpital Wojewódzki nr 1",
    organ_postepowania: null,
    czy_wypadek_podczas_uzywania_maszyny: false,
    imie_zglaszajacego: "Łukasz",
    nazwisko_zglaszajacego: "Szczepanik",
    nr_telefonu_zglaszajacego: "+48 515 444 111",
  }),
  createDocument({
    id: 9,
    pesel: "84030321009",
    nr_dowodu: "IIR223344",
    imie: "Artur",
    nazwisko: "Kulesza",
    data_urodzenia: "1984-03-03",
    miejsce_urodzenia: "Białystok",
    numer_telefonu: "+48 605 555 777",
    ulica: "Partyzantów",
    nr_domu: "6",
    nr_lokalu: null,
    miejscowosc: "Białystok",
    kod_pocztowy: "15-001",
    data_wypadku: "2025-12-02",
    godzina_wypadku: "12:05",
    miejsce_wypadku: "Warsztat serwisowy autobusów",
    planowana_godzina_rozpoczecia_pracy: "08:00",
    planowana_godzina_zakonczenia_pracy: "16:00",
    rodzaj_urazow: "Poparzenie przedramienia",
    szczegoly_okolicznosci:
      "W trakcie odkręcania przewodu chłodnicy doszło do gwałtownego wyrzutu pary wodnej.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "Szpital Wojewódzki w Białymstoku",
    organ_postepowania: "PIP Białystok",
    czy_wypadek_podczas_uzywania_maszyny: true,
    opis_maszyn: "Podnośnik hydrauliczny kolumnowy",
    czy_maszyna_posiada_atest: true,
    czy_maszyna_w_ewidencji: true,
    imie_zglaszajacego: "Artur",
    nazwisko_zglaszajacego: "Kulesza",
    nr_telefonu_zglaszajacego: "+48 605 555 777",
  }),
  createDocument({
    id: 10,
    pesel: "91061890807",
    nr_dowodu: "JJJ556677",
    imie: "Adrianna",
    nazwisko: "Kasperska",
    data_urodzenia: "1991-06-18",
    miejsce_urodzenia: "Szczecin",
    numer_telefonu: "+48 733 811 122",
    ulica: "Żaglowa",
    nr_domu: "12",
    nr_lokalu: "3",
    miejscowosc: "Szczecin",
    kod_pocztowy: "70-653",
    data_wypadku: "2025-12-03",
    godzina_wypadku: "07:10",
    miejsce_wypadku: "Stocznia, sekcja kadłubowa",
    planowana_godzina_rozpoczecia_pracy: "06:00",
    planowana_godzina_zakonczenia_pracy: "14:00",
    rodzaj_urazow: "Stłuczenie barku",
    szczegoly_okolicznosci:
      "Podczas przenoszenia płyt stalowych chwytak magnetyczny poluzował się, a element uderzył pracownicę w ramię.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "Przychodnia zakładowa",
    organ_postepowania: "PIP Szczecin",
    czy_wypadek_podczas_uzywania_maszyny: true,
    opis_maszyn: "Suwnica bramowa",
    czy_maszyna_posiada_atest: true,
    czy_maszyna_w_ewidencji: true,
    imie_zglaszajacego: "Grzegorz",
    nazwisko_zglaszajacego: "Mazurek",
    nr_telefonu_zglaszajacego: "+48 790 666 331",
    witnesses: [
      {
        imie: "Marcin",
        nazwisko: "Żurawski",
        ulica: "Rajska",
        nr_domu: "9",
        nr_lokalu: "7",
        miejscowosc: "Szczecin",
        kod_pocztowy: "70-653",
        nazwa_panstwa: "Polska",
        document: 10,
      },
    ],
  }),
  createDocument({
    id: 11,
    pesel: "79010411223",
    nr_dowodu: "KKK667788",
    imie: "Tomasz",
    nazwisko: "Szopa",
    data_urodzenia: "1979-01-04",
    miejsce_urodzenia: "Katowice",
    numer_telefonu: "+48 601 900 111",
    ulica: "Bukowa",
    nr_domu: "10",
    nr_lokalu: null,
    miejscowosc: "Katowice",
    kod_pocztowy: "40-129",
    data_wypadku: "2025-12-04",
    godzina_wypadku: "18:25",
    miejsce_wypadku: "Kopalnia, oddział przygotowania materiałów wybuchowych",
    planowana_godzina_rozpoczecia_pracy: "14:00",
    planowana_godzina_zakonczenia_pracy: "22:00",
    rodzaj_urazow: "Poparzenia I stopnia",
    szczegoly_okolicznosci: "Detonator samozapłonowy uaktywnił się w trakcie sprawdzania przewodów.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "Szpital Wojewódzki w Katowicach",
    organ_postepowania: "WUG Katowice",
    czy_wypadek_podczas_uzywania_maszyny: true,
    opis_maszyn: "Stół do przygotowania ładunków",
    czy_maszyna_posiada_atest: true,
    czy_maszyna_w_ewidencji: true,
    imie_zglaszajacego: "Tomasz",
    nazwisko_zglaszajacego: "Szopa",
    nr_telefonu_zglaszajacego: "+48 601 900 111",
  }),
  createDocument({
    id: 12,
    pesel: "86031233445",
    nr_dowodu: "LLL778899",
    imie: "Joanna",
    nazwisko: "Bednarek",
    data_urodzenia: "1986-03-12",
    miejsce_urodzenia: "Bydgoszcz",
    numer_telefonu: "+48 789 120 450",
    ulica: "Lesna",
    nr_domu: "5",
    nr_lokalu: "8",
    miejscowosc: "Bydgoszcz",
    kod_pocztowy: "85-635",
    data_wypadku: "2025-12-05",
    godzina_wypadku: "13:35",
    miejsce_wypadku: "Centrum logistyczne, strefa kompletacji",
    planowana_godzina_rozpoczecia_pracy: "10:00",
    planowana_godzina_zakonczenia_pracy: "18:00",
    rodzaj_urazow: "Uszkodzenie więzadeł kolana",
    szczegoly_okolicznosci:
      "Pracownica potknęła się o niezabezpieczoną paletę i upadła, skręcając kolano.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "Szpital Uniwersytecki nr 2 w Bydgoszczy",
    organ_postepowania: null,
    czy_wypadek_podczas_uzywania_maszyny: false,
    imie_zglaszajacego: "Joanna",
    nazwisko_zglaszajacego: "Bednarek",
    nr_telefonu_zglaszajacego: "+48 789 120 450",
  }),
  createDocument({
    id: 13,
    pesel: "99041944556",
    nr_dowodu: "MMM889900",
    imie: "Kacper",
    nazwisko: "Pawlak",
    data_urodzenia: "1999-04-19",
    miejsce_urodzenia: "Opole",
    numer_telefonu: "+48 532 001 889",
    ulica: "Szkolna",
    nr_domu: "3",
    nr_lokalu: null,
    miejscowosc: "Opole",
    kod_pocztowy: "45-094",
    data_wypadku: "2025-12-06",
    godzina_wypadku: "15:05",
    miejsce_wypadku: "Warsztat stolarski",
    planowana_godzina_rozpoczecia_pracy: "07:00",
    planowana_godzina_zakonczenia_pracy: "15:00",
    rodzaj_urazow: "Odcięcie fragmentu palca",
    szczegoly_okolicznosci: "Nie zastosowano osłony tarczy podczas docinania elementów.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "SOR Opole",
    organ_postepowania: "PIP Opole",
    czy_wypadek_podczas_uzywania_maszyny: true,
    opis_maszyn: "Pilarka tarczowa stołowa",
    czy_maszyna_posiada_atest: true,
    czy_maszyna_w_ewidencji: true,
    imie_zglaszajacego: "Michał",
    nazwisko_zglaszajacego: "Bartek",
    nr_telefonu_zglaszajacego: "+48 721 998 221",
    witnesses: [
      {
        imie: "Damian",
        nazwisko: "Sowa",
        ulica: "Kołłątaja",
        nr_domu: "7",
        nr_lokalu: null,
        miejscowosc: "Opole",
        kod_pocztowy: "45-064",
        nazwa_panstwa: "Polska",
        document: 13,
      },
    ],
  }),
  createDocument({
    id: 14,
    pesel: "88081255667",
    nr_dowodu: "NNN990011",
    imie: "Karolina",
    nazwisko: "Serafin",
    data_urodzenia: "1988-08-12",
    miejsce_urodzenia: "Koszalin",
    numer_telefonu: "+48 690 555 001",
    ulica: "Parkowa",
    nr_domu: "30",
    nr_lokalu: "9",
    miejscowosc: "Koszalin",
    kod_pocztowy: "75-502",
    data_wypadku: "2025-12-07",
    godzina_wypadku: "11:30",
    miejsce_wypadku: "Call center, sala operacyjna",
    planowana_godzina_rozpoczecia_pracy: "08:00",
    planowana_godzina_zakonczenia_pracy: "16:00",
    rodzaj_urazow: "Silny ból kręgosłupa",
    szczegoly_okolicznosci:
      "Podczas przenoszenia pudeł z archiwum pracownica doznała nagłego bólu pleców.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "Pogotowie ratunkowe",
    organ_postepowania: null,
    czy_wypadek_podczas_uzywania_maszyny: false,
    imie_zglaszajacego: "Karolina",
    nazwisko_zglaszajacego: "Serafin",
    nr_telefonu_zglaszajacego: "+48 690 555 001",
  }),
  createDocument({
    id: 15,
    pesel: "78010166778",
    nr_dowodu: "OOO101112",
    imie: "Paweł",
    nazwisko: "Domagała",
    data_urodzenia: "1978-01-01",
    miejsce_urodzenia: "Gliwice",
    numer_telefonu: "+48 602 345 765",
    ulica: "Ptasia",
    nr_domu: "44",
    nr_lokalu: "2",
    miejscowosc: "Gliwice",
    kod_pocztowy: "44-100",
    data_wypadku: "2025-12-08",
    godzina_wypadku: "04:50",
    miejsce_wypadku: "Hala hutnicza, piec elektryczny",
    planowana_godzina_rozpoczecia_pracy: "22:00",
    planowana_godzina_zakonczenia_pracy: "06:00",
    rodzaj_urazow: "Oparzenia twarzy i szyi",
    szczegoly_okolicznosci:
      "Podczas kontroli wsadu nastąpił nagły wyrzut płynnego metalu.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "Centrum Leczenia Oparzeń w Siemianowicach",
    organ_postepowania: "PIP Katowice",
    czy_wypadek_podczas_uzywania_maszyny: true,
    opis_maszyn: "Piec łukowy",
    czy_maszyna_posiada_atest: true,
    czy_maszyna_w_ewidencji: true,
    imie_zglaszajacego: "Andrzej",
    nazwisko_zglaszajacego: "Kula",
    nr_telefonu_zglaszajacego: "+48 601 244 332",
    witnesses: [
      {
        imie: "Robert",
        nazwisko: "Fitas",
        ulica: "Chemiczna",
        nr_domu: "5",
        nr_lokalu: null,
        miejscowosc: "Gliwice",
        kod_pocztowy: "44-121",
        nazwa_panstwa: "Polska",
        document: 15,
      },
    ],
  }),
  createDocument({
    id: 16,
    pesel: "91071277889",
    nr_dowodu: "PPP212223",
    imie: "Magdalena",
    nazwisko: "Kwaśniewska",
    data_urodzenia: "1991-07-12",
    miejsce_urodzenia: "Bytom",
    numer_telefonu: "+48 720 660 552",
    ulica: "Angelusa",
    nr_domu: "16",
    nr_lokalu: "4",
    miejscowosc: "Bytom",
    kod_pocztowy: "41-902",
    data_wypadku: "2025-12-09",
    godzina_wypadku: "17:40",
    miejsce_wypadku: "Szkoła językowa, sala lekcyjna",
    planowana_godzina_rozpoczecia_pracy: "14:00",
    planowana_godzina_zakonczenia_pracy: "20:00",
    rodzaj_urazow: "Złamanie kostki bocznej",
    szczegoly_okolicznosci: "Upadek ze schodów podczas ewakuacji próbnej. Schody były śliskie po świeżym myciu.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "Szpital w Bytomiu",
    organ_postepowania: null,
    czy_wypadek_podczas_uzywania_maszyny: false,
    imie_zglaszajacego: "Magdalena",
    nazwisko_zglaszajacego: "Kwaśniewska",
    nr_telefonu_zglaszajacego: "+48 720 660 552",
  }),
  createDocument({
    id: 17,
    pesel: "89093088990",
    nr_dowodu: "QQQ323334",
    imie: "Konrad",
    nazwisko: "Brzoza",
    data_urodzenia: "1989-09-30",
    miejsce_urodzenia: "Kielce",
    numer_telefonu: "+48 640 990 221",
    ulica: "Ogrodowa",
    nr_domu: "11",
    nr_lokalu: null,
    miejscowosc: "Kielce",
    kod_pocztowy: "25-025",
    data_wypadku: "2025-12-10",
    godzina_wypadku: "19:55",
    miejsce_wypadku: "Serwerownia, dział IT",
    planowana_godzina_rozpoczecia_pracy: "15:00",
    planowana_godzina_zakonczenia_pracy: "23:00",
    rodzaj_urazow: "Porażenie prądem",
    szczegoly_okolicznosci:
      "Podczas wymiany zasilacza pracownik dotknął odsłoniętych przewodów w szafie rack.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "Pogotowie ratunkowe Kielce",
    organ_postepowania: "PIP Kielce",
    czy_wypadek_podczas_uzywania_maszyny: true,
    opis_maszyn: "Szafa serwerowa z systemem UPS",
    czy_maszyna_posiada_atest: true,
    czy_maszyna_w_ewidencji: true,
    imie_zglaszajacego: "Zofia",
    nazwisko_zglaszajacego: "Grabska",
    nr_telefonu_zglaszajacego: "+48 640 990 300",
  }),
  createDocument({
    id: 18,
    pesel: "97021599001",
    nr_dowodu: "RRR434445",
    imie: "Marta",
    nazwisko: "Kalinowska",
    data_urodzenia: "1997-02-15",
    miejsce_urodzenia: "Suwałki",
    numer_telefonu: "+48 515 770 900",
    ulica: "Suwalska",
    nr_domu: "19",
    nr_lokalu: "10",
    miejscowosc: "Warszawa",
    kod_pocztowy: "03-111",
    data_wypadku: "2025-12-11",
    godzina_wypadku: "09:25",
    miejsce_wypadku: "Biuro księgowe, archiwum",
    planowana_godzina_rozpoczecia_pracy: "08:00",
    planowana_godzina_zakonczenia_pracy: "16:00",
    rodzaj_urazow: "Uraz głowy",
    szczegoly_okolicznosci: "Upadek segregatora z wysokiego regału na głowę pracownicy.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "Szpital Praski",
    organ_postepowania: null,
    czy_wypadek_podczas_uzywania_maszyny: false,
    imie_zglaszajacego: "Marta",
    nazwisko_zglaszajacego: "Kalinowska",
    nr_telefonu_zglaszajacego: "+48 515 770 900",
  }),
  createDocument({
    id: 19,
    pesel: "86040410101",
    nr_dowodu: "SSS545546",
    imie: "Igor",
    nazwisko: "Kozłowski",
    data_urodzenia: "1986-04-04",
    miejsce_urodzenia: "Lublin",
    numer_telefonu: "+48 607 708 509",
    ulica: "Narutowicza",
    nr_domu: "28",
    nr_lokalu: "5",
    miejscowosc: "Lublin",
    kod_pocztowy: "20-016",
    data_wypadku: "2025-12-12",
    godzina_wypadku: "08:35",
    miejsce_wypadku: "Laboratorium mikrobiologiczne",
    planowana_godzina_rozpoczecia_pracy: "07:00",
    planowana_godzina_zakonczenia_pracy: "15:00",
    rodzaj_urazow: "Skaleczenie i ekspozycja biologiczna",
    szczegoly_okolicznosci:
      "Strzykawka z jednorazową igłą odskoczyła podczas utylizacji w kontenerze.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "Oddział chorób zakaźnych Szpitala Wojewódzkiego",
    organ_postepowania: null,
    czy_wypadek_podczas_uzywania_maszyny: false,
    imie_zglaszajacego: "Igor",
    nazwisko_zglaszajacego: "Kozłowski",
    nr_telefonu_zglaszajacego: "+48 607 708 509",
  }),
  createDocument({
    id: 20,
    pesel: "90010121212",
    nr_dowodu: "TTT656657",
    imie: "Patryk",
    nazwisko: "Woźniak",
    data_urodzenia: "1990-01-01",
    miejsce_urodzenia: "Zielona Góra",
    numer_telefonu: "+48 500 250 120",
    ulica: "Jagodowa",
    nr_domu: "8",
    nr_lokalu: null,
    miejscowosc: "Zielona Góra",
    kod_pocztowy: "65-120",
    data_wypadku: "2025-12-13",
    godzina_wypadku: "14:10",
    miejsce_wypadku: "Linia montażu rowerów",
    planowana_godzina_rozpoczecia_pracy: "06:00",
    planowana_godzina_zakonczenia_pracy: "14:00",
    rodzaj_urazow: "Stłuczenie klatki piersiowej",
    szczegoly_okolicznosci:
      "Operator wózka widłowego zahamował gwałtownie, przewracając paletę z elementami na pracownika.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "Szpital Uniwersytecki Zielona Góra",
    organ_postepowania: "PIP Zielona Góra",
    czy_wypadek_podczas_uzywania_maszyny: true,
    opis_maszyn: "Wózek widłowy elektryczny",
    czy_maszyna_posiada_atest: true,
    czy_maszyna_w_ewidencji: true,
    imie_zglaszajacego: "Monika",
    nazwisko_zglaszajacego: "Lis",
    nr_telefonu_zglaszajacego: "+48 500 250 130",
  }),
  createDocument({
    id: 21,
    pesel: "94071532323",
    nr_dowodu: "UUU767768",
    imie: "Olga",
    nazwisko: "Nowińska",
    data_urodzenia: "1994-07-15",
    miejsce_urodzenia: "Słupsk",
    numer_telefonu: "+48 604 903 402",
    ulica: "Kasprowicza",
    nr_domu: "12",
    nr_lokalu: "3",
    miejscowosc: "Gdańsk",
    kod_pocztowy: "80-411",
    data_wypadku: "2025-12-14",
    godzina_wypadku: "12:45",
    miejsce_wypadku: "Strefa testów urządzeń elektronicznych",
    planowana_godzina_rozpoczecia_pracy: "08:00",
    planowana_godzina_zakonczenia_pracy: "16:00",
    rodzaj_urazow: "Oparzenie chemiczne",
    szczegoly_okolicznosci:
      "Rozlany elektrolit z baterii litowej dostał się na skórę technika.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "Szpital Copernicus",
    organ_postepowania: null,
    czy_wypadek_podczas_uzywania_maszyny: true,
    opis_maszyn: "Stanowisko testowe baterii",
    czy_maszyna_posiada_atest: true,
    czy_maszyna_w_ewidencji: true,
    imie_zglaszajacego: "Olga",
    nazwisko_zglaszajacego: "Nowińska",
    nr_telefonu_zglaszajacego: "+48 604 903 402",
  }),
  createDocument({
    id: 22,
    pesel: "83011143434",
    nr_dowodu: "VVV878879",
    imie: "Sebastian",
    nazwisko: "Lach",
    data_urodzenia: "1983-01-11",
    miejsce_urodzenia: "Nowy Sącz",
    numer_telefonu: "+48 601 707 606",
    ulica: "Górska",
    nr_domu: "4",
    nr_lokalu: null,
    miejscowosc: "Nowy Sącz",
    kod_pocztowy: "33-300",
    data_wypadku: "2025-12-15",
    godzina_wypadku: "05:55",
    miejsce_wypadku: "Skład drewna, tartak",
    planowana_godzina_rozpoczecia_pracy: "06:00",
    planowana_godzina_zakonczenia_pracy: "14:00",
    rodzaj_urazow: "Złamanie kości udowej",
    szczegoly_okolicznosci:
      "Suwacze liny źle zabezpieczone. Kłody drewna stoczyły się z rampy i przygniotły pracownika.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "Szpital Specjalistyczny Nowy Sącz",
    organ_postepowania: "PIP Kraków",
    czy_wypadek_podczas_uzywania_maszyny: true,
    opis_maszyn: "Żuraw leśny",
    czy_maszyna_posiada_atest: true,
    czy_maszyna_w_ewidencji: true,
    imie_zglaszajacego: "Sebastian",
    nazwisko_zglaszajacego: "Lach",
    nr_telefonu_zglaszajacego: "+48 601 707 606",
    witnesses: [
      {
        imie: "Rafał",
        nazwisko: "Pałka",
        ulica: "Świerkowa",
        nr_domu: "1",
        nr_lokalu: null,
        miejscowosc: "Nowy Sącz",
        kod_pocztowy: "33-310",
        nazwa_panstwa: "Polska",
        document: 22,
      },
    ],
  }),
  createDocument({
    id: 23,
    pesel: "96090254545",
    nr_dowodu: "WWW989990",
    imie: "Alicja",
    nazwisko: "Rybak",
    data_urodzenia: "1996-09-02",
    miejsce_urodzenia: "Bielsko-Biała",
    numer_telefonu: "+48 511 655 404",
    ulica: "Orla",
    nr_domu: "18",
    nr_lokalu: "2",
    miejscowosc: "Bielsko-Biała",
    kod_pocztowy: "43-300",
    data_wypadku: "2025-12-16",
    godzina_wypadku: "07:25",
    miejsce_wypadku: "Apteka, zaplecze",
    planowana_godzina_rozpoczecia_pracy: "07:00",
    planowana_godzina_zakonczenia_pracy: "15:00",
    rodzaj_urazow: "Uraz kręgosłupa szyjnego",
    szczegoly_okolicznosci:
      "Pracownica dźwigała kartony z lekami powyżej normy i poślizgnęła się na mokrej posadzce.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "Szpital Wojewódzki w Bielsku-Białej",
    organ_postepowania: null,
    czy_wypadek_podczas_uzywania_maszyny: false,
    imie_zglaszajacego: "Alicja",
    nazwisko_zglaszajacego: "Rybak",
    nr_telefonu_zglaszajacego: "+48 511 655 404",
  }),
  createDocument({
    id: 24,
    pesel: "85062365656",
    nr_dowodu: "XXX090101",
    imie: "Mirosław",
    nazwisko: "Góra",
    data_urodzenia: "1985-06-23",
    miejsce_urodzenia: "Leszno",
    numer_telefonu: "+48 603 233 880",
    ulica: "Czarnoleska",
    nr_domu: "24",
    nr_lokalu: null,
    miejscowosc: "Leszno",
    kod_pocztowy: "64-100",
    data_wypadku: "2025-12-17",
    godzina_wypadku: "23:05",
    miejsce_wypadku: "Elektrownia biomasowa, sterownia",
    planowana_godzina_rozpoczecia_pracy: "18:00",
    planowana_godzina_zakonczenia_pracy: "06:00",
    rodzaj_urazow: "Zatrucie tlenkiem węgla",
    szczegoly_okolicznosci: "Nieprawidłowo działająca wentylacja w sterowni, wzrost stężenia CO w powietrzu.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "Szpital Wojewódzki w Lesznie",
    organ_postepowania: "PIP Poznań",
    czy_wypadek_podczas_uzywania_maszyny: true,
    opis_maszyn: "System pieca fluidalnego",
    czy_maszyna_posiada_atest: true,
    czy_maszyna_w_ewidencji: true,
    imie_zglaszajacego: "Patrycja",
    nazwisko_zglaszajacego: "Ziółkowska",
    nr_telefonu_zglaszajacego: "+48 603 233 881",
  }),
  createDocument({
    id: 25,
    pesel: "91011976767",
    nr_dowodu: "YYY101112",
    imie: "Paulina",
    nazwisko: "Cholewa",
    data_urodzenia: "1991-01-19",
    miejsce_urodzenia: "Kalisz",
    numer_telefonu: "+48 501 899 700",
    ulica: "Tęczowa",
    nr_domu: "6",
    nr_lokalu: "1",
    miejscowosc: "Wrocław",
    kod_pocztowy: "53-601",
    data_wypadku: "2025-12-18",
    godzina_wypadku: "10:05",
    miejsce_wypadku: "Studio fotograficzne",
    planowana_godzina_rozpoczecia_pracy: "09:00",
    planowana_godzina_zakonczenia_pracy: "17:00",
    rodzaj_urazow: "Oparzenie lampą błyskową",
    szczegoly_okolicznosci:
      "Żarówka halogenowa pękła podczas wymiany, powodując poparzenia dłoni.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "Szpital im. Borowskiego we Wrocławiu",
    organ_postepowania: null,
    czy_wypadek_podczas_uzywania_maszyny: true,
    opis_maszyn: "Lampa studyjna 1200W",
    czy_maszyna_posiada_atest: true,
    czy_maszyna_w_ewidencji: true,
    imie_zglaszajacego: "Paulina",
    nazwisko_zglaszajacego: "Cholewa",
    nr_telefonu_zglaszajacego: "+48 501 899 700",
  }),
  createDocument({
    id: 26,
    pesel: "78091487878",
    nr_dowodu: "ZZZ212223",
    imie: "Rafał",
    nazwisko: "Jagiełło",
    data_urodzenia: "1978-09-14",
    miejsce_urodzenia: "Siedlce",
    numer_telefonu: "+48 604 321 211",
    ulica: "Grunwaldzka",
    nr_domu: "17",
    nr_lokalu: "6",
    miejscowosc: "Siedlce",
    kod_pocztowy: "08-110",
    data_wypadku: "2025-12-19",
    godzina_wypadku: "01:15",
    miejsce_wypadku: "Centrum dystrybucji, dok załadunkowy",
    planowana_godzina_rozpoczecia_pracy: "22:00",
    planowana_godzina_zakonczenia_pracy: "06:00",
    rodzaj_urazow: "Zwichnięcie barku",
    szczegoly_okolicznosci:
      "Operator wózka zsunął się z rampy podczas cofania, Rafał próbował go asekurować.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "Szpital Powiatowy w Siedlcach",
    organ_postepowania: null,
    czy_wypadek_podczas_uzywania_maszyny: true,
    opis_maszyn: "Wózek paletowy",
    czy_maszyna_posiada_atest: true,
    czy_maszyna_w_ewidencji: true,
    imie_zglaszajacego: "Rafał",
    nazwisko_zglaszajacego: "Jagiełło",
    nr_telefonu_zglaszajacego: "+48 604 321 211",
  }),
  createDocument({
    id: 27,
    pesel: "92021198989",
    nr_dowodu: "AAA232425",
    imie: "Izabela",
    nazwisko: "Majewska",
    data_urodzenia: "1992-02-11",
    miejsce_urodzenia: "Gorzów Wielkopolski",
    numer_telefonu: "+48 723 410 512",
    ulica: "Słoneczna",
    nr_domu: "2",
    nr_lokalu: "2",
    miejscowosc: "Gorzów Wielkopolski",
    kod_pocztowy: "66-400",
    data_wypadku: "2025-12-20",
    godzina_wypadku: "18:05",
    miejsce_wypadku: "Hotel, kuchnia",
    planowana_godzina_rozpoczecia_pracy: "12:00",
    planowana_godzina_zakonczenia_pracy: "20:00",
    rodzaj_urazow: "Poważne oparzenia dłoni",
    szczegoly_okolicznosci:
      "Rozszczelniony garnek ciśnieniowy wystrzelił gorącym sosem podczas odkręcania pokrywy.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "Wojewódzki Szpital w Gorzowie",
    organ_postepowania: null,
    czy_wypadek_podczas_uzywania_maszyny: true,
    opis_maszyn: "Garnek ciśnieniowy 30L",
    czy_maszyna_posiada_atest: true,
    czy_maszyna_w_ewidencji: true,
    imie_zglaszajacego: "Izabela",
    nazwisko_zglaszajacego: "Majewska",
    nr_telefonu_zglaszajacego: "+48 723 410 512",
  }),
  createDocument({
    id: 28,
    pesel: "99050109090",
    nr_dowodu: "BBB343536",
    imie: "Łukasz",
    nazwisko: "Sawicki",
    data_urodzenia: "1999-05-01",
    miejsce_urodzenia: "Olsztyn",
    numer_telefonu: "+48 792 660 442",
    ulica: "Borowa",
    nr_domu: "13",
    nr_lokalu: null,
    miejscowosc: "Olsztyn",
    kod_pocztowy: "10-900",
    data_wypadku: "2025-12-21",
    godzina_wypadku: "03:40",
    miejsce_wypadku: "Zakład produkcji mebli, lakiernia",
    planowana_godzina_rozpoczecia_pracy: "22:00",
    planowana_godzina_zakonczenia_pracy: "06:00",
    rodzaj_urazow: "Wstrząśnienie mózgu",
    szczegoly_okolicznosci:
      "Oślepienie przez błysk jarzeniowy podczas czyszczenia kabiny, potknięcie i uderzenie głową o posadzkę.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "Szpital Wojewódzki w Olsztynie",
    organ_postepowania: null,
    czy_wypadek_podczas_uzywania_maszyny: true,
    opis_maszyn: "Kabina lakiernicza",
    czy_maszyna_posiada_atest: true,
    czy_maszyna_w_ewidencji: true,
    imie_zglaszajacego: "Łukasz",
    nazwisko_zglaszajacego: "Sawicki",
    nr_telefonu_zglaszajacego: "+48 792 660 442",
  }),
  createDocument({
    id: 29,
    pesel: "87011220202",
    nr_dowodu: "CCC454647",
    imie: "Eryk",
    nazwisko: "Krupa",
    data_urodzenia: "1987-01-12",
    miejsce_urodzenia: "Łomża",
    numer_telefonu: "+48 601 552 997",
    ulica: "Źródlana",
    nr_domu: "5",
    nr_lokalu: null,
    miejscowosc: "Łomża",
    kod_pocztowy: "18-400",
    data_wypadku: "2025-12-22",
    godzina_wypadku: "13:20",
    miejsce_wypadku: "Zakład mleczarski, linia butelkowania",
    planowana_godzina_rozpoczecia_pracy: "05:00",
    planowana_godzina_zakonczenia_pracy: "13:00",
    rodzaj_urazow: "Skażenie chemiczne oka",
    szczegoly_okolicznosci:
      "Czyszczenie głowicy napełniającej bez osłony. Środek myjący dostał się do oka.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "Szpital Wojewódzki w Łomży",
    organ_postepowania: null,
    czy_wypadek_podczas_uzywania_maszyny: true,
    opis_maszyn: "Automat do butelkowania",
    czy_maszyna_posiada_atest: true,
    czy_maszyna_w_ewidencji: true,
    imie_zglaszajacego: "Eryk",
    nazwisko_zglaszajacego: "Krupa",
    nr_telefonu_zglaszajacego: "+48 601 552 997",
  }),
  createDocument({
    id: 30,
    pesel: "98122931313",
    nr_dowodu: "DDD565758",
    imie: "Weronika",
    nazwisko: "Kopeć",
    data_urodzenia: "1998-12-29",
    miejsce_urodzenia: "Płock",
    numer_telefonu: "+48 698 301 778",
    ulica: "Zbożowa",
    nr_domu: "9",
    nr_lokalu: "4",
    miejscowosc: "Płock",
    kod_pocztowy: "09-400",
    data_wypadku: "2025-12-23",
    godzina_wypadku: "09:50",
    miejsce_wypadku: "Laboratorium petrochemiczne",
    planowana_godzina_rozpoczecia_pracy: "07:00",
    planowana_godzina_zakonczenia_pracy: "15:00",
    rodzaj_urazow: "Podrażnienie dróg oddechowych",
    szczegoly_okolicznosci:
      "Podczas kalibracji czujników doszło do ulatniania się oparów benzenu.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "Szpital Wojewódzki w Płocku",
    organ_postepowania: "PIP Płock",
    czy_wypadek_podczas_uzywania_maszyny: true,
    opis_maszyn: "Instalacja chromatografu",
    czy_maszyna_posiada_atest: true,
    czy_maszyna_w_ewidencji: true,
    imie_zglaszajacego: "Weronika",
    nazwisko_zglaszajacego: "Kopeć",
    nr_telefonu_zglaszajacego: "+48 698 301 778",
  }),
  createDocument({
    id: 31,
    pesel: "87050142424",
    nr_dowodu: "EEE676869",
    imie: "Marek",
    nazwisko: "Groch",
    data_urodzenia: "1987-05-01",
    miejsce_urodzenia: "Zamość",
    numer_telefonu: "+48 602 411 700",
    ulica: "Hetmańska",
    nr_domu: "11",
    nr_lokalu: null,
    miejscowosc: "Zamość",
    kod_pocztowy: "22-400",
    data_wypadku: "2025-12-24",
    godzina_wypadku: "11:40",
    miejsce_wypadku: "Zakład przetwórstwa mięsa",
    planowana_godzina_rozpoczecia_pracy: "05:00",
    planowana_godzina_zakonczenia_pracy: "13:00",
    rodzaj_urazow: "Głębokie skaleczenie dłoni",
    szczegoly_okolicznosci:
      "Podczas cięcia schabu maszyną taśmową ostrze zsunęło się z prowadnicy.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "Szpital Jana Pawła II w Zamościu",
    organ_postepowania: "PIP Lublin",
    czy_wypadek_podczas_uzywania_maszyny: true,
    opis_maszyn: "Piła taśmowa do mięsa",
    czy_maszyna_posiada_atest: true,
    czy_maszyna_w_ewidencji: true,
    imie_zglaszajacego: "Marek",
    nazwisko_zglaszajacego: "Groch",
    nr_telefonu_zglaszajacego: "+48 602 411 700",
  }),
  createDocument({
    id: 32,
    pesel: "90071653535",
    nr_dowodu: "FFF787879",
    imie: "Zuzanna",
    nazwisko: "Kubicka",
    data_urodzenia: "1990-07-16",
    miejsce_urodzenia: "Piła",
    numer_telefonu: "+48 780 119 235",
    ulica: "Spacerowa",
    nr_domu: "4",
    nr_lokalu: "2",
    miejscowosc: "Piła",
    kod_pocztowy: "64-920",
    data_wypadku: "2025-12-25",
    godzina_wypadku: "09:20",
    miejsce_wypadku: "Sklep wielkopowierzchniowy, dział dekoracji",
    planowana_godzina_rozpoczecia_pracy: "08:00",
    planowana_godzina_zakonczenia_pracy: "16:00",
    rodzaj_urazow: "Złamanie przedramienia",
    szczegoly_okolicznosci:
      "Pracownica była na drabinie uzupełniając ekspozycję, drabina się przewróciła.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "Szpital Specjalistyczny w Pile",
    organ_postepowania: null,
    czy_wypadek_podczas_uzywania_maszyny: false,
    imie_zglaszajacego: "Zuzanna",
    nazwisko_zglaszajacego: "Kubicka",
    nr_telefonu_zglaszajacego: "+48 780 119 235",
  }),
  createDocument({
    id: 33,
    pesel: "91020864646",
    nr_dowodu: "GGG898990",
    imie: "Karol",
    nazwisko: "Lisowski",
    data_urodzenia: "1991-02-08",
    miejsce_urodzenia: "Warszawa",
    numer_telefonu: "+48 601 821 550",
    ulica: "Saska",
    nr_domu: "23",
    nr_lokalu: "12",
    miejscowosc: "Warszawa",
    kod_pocztowy: "03-908",
    data_wypadku: "2025-12-26",
    godzina_wypadku: "20:30",
    miejsce_wypadku: "Studio telewizyjne",
    planowana_godzina_rozpoczecia_pracy: "14:00",
    planowana_godzina_zakonczenia_pracy: "22:00",
    rodzaj_urazow: "Upadek z podestu",
    szczegoly_okolicznosci:
      "Podczas ustawiania reflektora scenicznego obsługa potknęła się o kabel i spadła z wysokości dwóch metrów.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "Szpital Grochowski",
    organ_postepowania: null,
    czy_wypadek_podczas_uzywania_maszyny: true,
    opis_maszyn: "System oświetleniowy",
    czy_maszyna_posiada_atest: true,
    czy_maszyna_w_ewidencji: true,
    imie_zglaszajacego: "Karol",
    nazwisko_zglaszajacego: "Lisowski",
    nr_telefonu_zglaszajacego: "+48 601 821 550",
  }),
  createDocument({
    id: 34,
    pesel: "95091475757",
    nr_dowodu: "HHH909101",
    imie: "Dorota",
    nazwisko: "Pietras",
    data_urodzenia: "1995-09-14",
    miejsce_urodzenia: "Łask",
    numer_telefonu: "+48 512 998 450",
    ulica: "Różana",
    nr_domu: "6",
    nr_lokalu: "3",
    miejscowosc: "Łódź",
    kod_pocztowy: "90-212",
    data_wypadku: "2025-12-27",
    godzina_wypadku: "16:50",
    miejsce_wypadku: "Zakład krawiecki",
    planowana_godzina_rozpoczecia_pracy: "06:00",
    planowana_godzina_zakonczenia_pracy: "14:00",
    rodzaj_urazow: "Nakłucie palca",
    szczegoly_okolicznosci: "Maszyna do szycia uległa awarii, igła uderzyła w palec przy próbie naprawy.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "Szpital im. Kopernika w Łodzi",
    organ_postepowania: null,
    czy_wypadek_podczas_uzywania_maszyny: true,
    opis_maszyn: "Przemysłowa maszyna do szycia",
    czy_maszyna_posiada_atest: true,
    czy_maszyna_w_ewidencji: true,
    imie_zglaszajacego: "Dorota",
    nazwisko_zglaszajacego: "Pietras",
    nr_telefonu_zglaszajacego: "+48 512 998 450",
  }),
  createDocument({
    id: 35,
    pesel: "88031286868",
    nr_dowodu: "III010203",
    imie: "Bartosz",
    nazwisko: "Nowicki",
    data_urodzenia: "1988-03-12",
    miejsce_urodzenia: "Sopot",
    numer_telefonu: "+48 690 440 880",
    ulica: "Bitwy pod Płowcami",
    nr_domu: "7",
    nr_lokalu: "5",
    miejscowosc: "Sopot",
    kod_pocztowy: "81-731",
    data_wypadku: "2025-12-28",
    godzina_wypadku: "07:30",
    miejsce_wypadku: "Wyciąg narciarski, stacja górna",
    planowana_godzina_rozpoczecia_pracy: "06:00",
    planowana_godzina_zakonczenia_pracy: "14:00",
    rodzaj_urazow: "Złamanie obojczyka",
    szczegoly_okolicznosci:
      "Podczas próby odblokowania krzesła wyciągu nastąpił nagły start liny i operator został pociągnięty.",
    czy_udzielona_pomoc: true,
    miejsce_udzielenia_pomocy: "Szpital Morski PCK w Gdyni",
    organ_postepowania: "PIP Gdańsk",
    czy_wypadek_podczas_uzywania_maszyny: true,
    opis_maszyn: "Wyciąg krzesełkowy",
    czy_maszyna_posiada_atest: true,
    czy_maszyna_w_ewidencji: true,
    imie_zglaszajacego: "Bartosz",
    nazwisko_zglaszajacego: "Nowicki",
    nr_telefonu_zglaszajacego: "+48 690 440 880",
  }),
];
