import type { CaseDocument, DocumentPriority, DocumentStatus } from "@/types/case-document";
import type { Document } from "@/types/document";

export const defaultDocumentData: Document = {
  id: undefined,
  pesel: "00000000000",
  nr_dowodu: "AAA000000",
  imie: "Nieznane",
  nazwisko: "Nieznane",
  data_urodzenia: "1980-01-01",
  miejsce_urodzenia: "Nieznane",
  numer_telefonu: null,
  ulica: "Brak danych",
  nr_domu: "0",
  nr_lokalu: null,
  miejscowosc: "Brak danych",
  kod_pocztowy: "00-000",
  nazwa_panstwa: "Polska",
  ulica_ostatniego_zamieszkania: null,
  nr_domu_ostatniego_zamieszkania: null,
  nr_lokalu_ostatniego_zamieszkania: null,
  miejscowosc_ostatniego_zamieszkania: null,
  kod_pocztowy_ostatniego_zamieszkania: null,
  typ_korespondencji: null,
  ulica_korespondencji: null,
  nr_domu_korespondencji: null,
  nr_lokalu_korespondencji: null,
  miejscowosc_korespondencji: null,
  kod_pocztowy_korespondencji: null,
  nazwa_panstwa_korespondencji: null,
  ulica_dzialalnosci: null,
  nr_domu_dzialalnosci: null,
  nr_lokalu_dzialalnosci: null,
  miejscowosc_dzialalnosci: null,
  kod_pocztowy_dzialalnosci: null,
  nr_telefonu_dzialalnosci: null,
  ulica_opieki: null,
  nr_domu_opieki: null,
  nr_lokalu_opieki: null,
  miejscowosc_opieki: null,
  kod_pocztowy_opieki: null,
  nr_telefonu_opieki: null,
  imie_zglaszajacego: "Nieznane",
  nazwisko_zglaszajacego: "Nieznane",
  pesel_zglaszajacego: null,
  nr_dowodu_zglaszajacego: null,
  data_urodzenia_zglaszajacego: null,
  nr_telefonu_zglaszajacego: null,
  ulica_zglaszajacego: null,
  nr_domu_zglaszajacego: null,
  nr_lokalu_zglaszajacego: null,
  miejscowosc_zglaszajacego: null,
  kod_pocztowy_zglaszajacego: null,
  ulica_zglaszajacego_ostatniego_zamieszkania: null,
  nr_domu_zglaszajacego_ostatniego_zamieszkania: null,
  nr_lokalu_zglaszajacego_ostatniego_zamieszkania: null,
  miejscowosc_zglaszajacego_ostatniego_zamieszkania: null,
  kod_pocztowy_zglaszajacego_ostatniego_zamieszkania: null,
  typ_korespondencji_zglaszajacego: null,
  ulica_korespondencji_zglaszajacego: null,
  nr_domu_korespondencji_zglaszajacego: null,
  nr_lokalu_korespondencji_zglaszajacego: null,
  miejscowosc_korespondencji_zglaszajacego: null,
  kod_pocztowy_korespondencji_zglaszajacego: null,
  nazwa_panstwa_korespondencji_zglaszajacego: null,
  data_wypadku: "2025-01-01",
  godzina_wypadku: "08:00",
  miejsce_wypadku: "Brak danych",
  planowana_godzina_rozpoczecia_pracy: "08:00",
  planowana_godzina_zakonczenia_pracy: "16:00",
  rodzaj_urazow: "Brak danych",
  szczegoly_okolicznosci: "Brak danych",
  czy_udzielona_pomoc: false,
  miejsce_udzielenia_pomocy: null,
  organ_postepowania: null,
  czy_wypadek_podczas_uzywania_maszyny: false,
  opis_maszyn: null,
  czy_maszyna_posiada_atest: null,
  czy_maszyna_w_ewidencji: null,
  witnesses: [],
};

type DocumentSeed = {
  documentId: string;
  caseNumber: string;
  title: string;
  description: string;
  category: string;
  priority: DocumentPriority;
  status: DocumentStatus;
  reporterName: string;
  reporterEmail: string;
  reporterPhone?: string;
  createdAt: string;
  updatedAt?: string;
  assignedTo?: string;
  notes?: string;
  documentData: Partial<Document>;
};

const createDocument = (seed: DocumentSeed): CaseDocument => {
  const createdAt = new Date(seed.createdAt);
  const updatedAt = new Date(seed.updatedAt ?? seed.createdAt);

  return {
    ...defaultDocumentData,
    ...seed.documentData,
    documentId: seed.documentId,
    caseNumber: seed.caseNumber,
    title: seed.title,
    description: seed.description,
    category: seed.category,
    priority: seed.priority,
    status: seed.status,
    reporterName: seed.reporterName,
    reporterEmail: seed.reporterEmail,
    reporterPhone: seed.reporterPhone,
    createdAt,
    updatedAt,
    assignedTo: seed.assignedTo,
    notes: seed.notes,
  };
};

export const mockDocuments: CaseDocument[] = [
  createDocument({
    documentId: "DOC-001",
    caseNumber: "2025/12/0001",
    title: "Upadek z rusztowania",
    description:
      "Podczas montażu konstrukcji stalowej poszkodowany poślizgnął się na oblodzonym pomoście i spadł z wysokości 4 metrów.",
    category: "Prace na wysokości",
    priority: "high",
    status: "pending",
    reporterName: "Jan Kowalski",
    reporterEmail: "jan.kowalski@example.com",
    reporterPhone: "+48 123 456 789",
    createdAt: "2025-12-01T08:15:00Z",
    documentData: {
      pesel: "90010112345",
      nr_dowodu: "AAR123456",
      imie: "Jan",
      nazwisko: "Kowalski",
      data_urodzenia: "1990-01-01",
      miejsce_urodzenia: "Warszawa",
      numer_telefonu: "+48 123 456 789",
      ulica: "Prosta",
      nr_domu: "12",
      nr_lokalu: "4",
      miejscowosc: "Warszawa",
      kod_pocztowy: "00-950",
      data_wypadku: "2025-11-26",
      godzina_wypadku: "14:35",
      miejsce_wypadku: "Budowa centrum logistycznego, Mokotów",
      planowana_godzina_rozpoczecia_pracy: "07:00",
      planowana_godzina_zakonczenia_pracy: "15:00",
      rodzaj_urazow: "Złamanie kości przedramienia",
      szczegoly_okolicznosci:
        "Poślizgnięcie na oblodzonej powierzchni rusztowania podczas montażu stalowych belek. Poszkodowany spadł na platformę zabezpieczającą i doznał urazu ręki.",
      czy_udzielona_pomoc: true,
      miejsce_udzielenia_pomocy: "SOR Szpitala na Wołoskiej",
      organ_postepowania: "PIP Warszawa",
      czy_wypadek_podczas_uzywania_maszyny: true,
      opis_maszyn: "Elektryczne rusztowanie przestawne",
      czy_maszyna_posiada_atest: true,
      czy_maszyna_w_ewidencji: true,
      imie_zglaszajacego: "Jan",
      nazwisko_zglaszajacego: "Kowalski",
      pesel_zglaszajacego: "90010112345",
      nr_dowodu_zglaszajacego: "AAR123456",
      nr_telefonu_zglaszajacego: "+48 123 456 789",
      ulica_zglaszajacego: "Prosta",
      nr_domu_zglaszajacego: "12",
      miejscowosc_zglaszajacego: "Warszawa",
      kod_pocztowy_zglaszajacego: "00-950",
      witnesses: [
        {
          imie: "Piotr",
          nazwisko: "Lis",
          ulica: "Płocka",
          nr_domu: "8",
          nr_lokalu: "2",
          miejscowosc: "Warszawa",
          kod_pocztowy: "01-231",
          nazwa_panstwa: "Polska",
          document: 1,
        },
      ],
    },
  }),
  createDocument({
    documentId: "DOC-002",
    caseNumber: "2025/12/0042",
    title: "Przygniecenie przy naprawie prasy",
    description:
      "Podczas serwisu prasy hydraulicznej doszło do niespodziewanego opadnięcia stołu roboczego i przygniecenia dłoni pracownika.",
    category: "Naprawy maszyn",
    priority: "critical",
    status: "in-progress",
    reporterName: "Anna Nowak",
    reporterEmail: "anna.nowak@example.com",
    reporterPhone: "+48 987 654 321",
    createdAt: "2025-11-28T10:30:00Z",
    assignedTo: "Tomasz Wiśniewski",
    documentData: {
      pesel: "87050567890",
      nr_dowodu: "BTR987654",
      imie: "Marek",
      nazwisko: "Fronczak",
      data_urodzenia: "1987-05-05",
      miejsce_urodzenia: "Łódź",
      numer_telefonu: "+48 600 200 155",
      ulica: "Łąkowa",
      nr_domu: "7",
      miejscowosc: "Łódź",
      kod_pocztowy: "90-562",
      data_wypadku: "2025-11-25",
      godzina_wypadku: "11:10",
      miejsce_wypadku: "Hala pras hydraulicznych w zakładzie produkcyjnym",
      planowana_godzina_rozpoczecia_pracy: "06:00",
      planowana_godzina_zakonczenia_pracy: "14:00",
      rodzaj_urazow: "Zmiażdżenie dwóch palców dłoni",
      szczegoly_okolicznosci:
        "Pracownik prowadził regulację czujników krańcowych. Doszło do awarii zaworu i stół opadł, przygniatając dłoń.",
      czy_udzielona_pomoc: true,
      miejsce_udzielenia_pomocy: "Szpital im. Kopernika w Łodzi",
      organ_postepowania: "PIP Łódź",
      czy_wypadek_podczas_uzywania_maszyny: true,
      opis_maszyn: "Prasa hydrauliczna 350 ton",
      czy_maszyna_posiada_atest: true,
      czy_maszyna_w_ewidencji: true,
      imie_zglaszajacego: "Anna",
      nazwisko_zglaszajacego: "Nowak",
      nr_telefonu_zglaszajacego: "+48 987 654 321",
      ulica_zglaszajacego: "Sienkiewicza",
      nr_domu_zglaszajacego: "20",
      miejscowosc_zglaszajacego: "Łódź",
      kod_pocztowy_zglaszajacego: "90-113",
    },
  }),
  createDocument({
    documentId: "DOC-003",
    caseNumber: "2025/12/0127",
    title: "Oparzenia chemiczne dłoni",
    description:
      "Podczas czyszczenia mieszalnika doszło do rozszczelnienia przewodu i kontaktu skóry z żrącym środkiem.",
    category: "Chemia i środki czyszczące",
    priority: "high",
    status: "pending",
    reporterName: "Maria Zielińska",
    reporterEmail: "maria.zielinska@example.com",
    createdAt: "2025-12-03T09:45:00Z",
    documentData: {
      pesel: "78032378901",
      nr_dowodu: "CCR556677",
      imie: "Ewelina",
      nazwisko: "Gajda",
      data_urodzenia: "1978-03-23",
      miejsce_urodzenia: "Poznań",
      numer_telefonu: "+48 501 222 333",
      ulica: "Wiosny Ludów",
      nr_domu: "3",
      miejscowosc: "Poznań",
      kod_pocztowy: "61-831",
      data_wypadku: "2025-12-02",
      godzina_wypadku: "07:50",
      miejsce_wypadku: "Linia rozlewnicza środków chemicznych",
      planowana_godzina_rozpoczecia_pracy: "06:00",
      planowana_godzina_zakonczenia_pracy: "14:00",
      rodzaj_urazow: "Oparzenia chemiczne dłoni",
      szczegoly_okolicznosci:
        "Rozłączenie złącza przy pracy rękawicą ochronną. Środek o pH 13 zalał rękawicę i spowodował oparzenia.",
      czy_udzielona_pomoc: true,
      miejsce_udzielenia_pomocy: "Szpital im. Raszei w Poznaniu",
      organ_postepowania: "PIP Poznań",
      czy_wypadek_podczas_uzywania_maszyny: false,
      opis_maszyn: null,
      czy_maszyna_posiada_atest: null,
      czy_maszyna_w_ewidencji: null,
      imie_zglaszajacego: "Maria",
      nazwisko_zglaszajacego: "Zielińska",
      nr_telefonu_zglaszajacego: "+48 500 111 111",
      ulica_zglaszajacego: "Ratajczaka",
      nr_domu_zglaszajacego: "15",
      miejscowosc_zglaszajacego: "Poznań",
      kod_pocztowy_zglaszajacego: "61-814",
    },
  }),
  createDocument({
    documentId: "DOC-004",
    caseNumber: "2025/11/0983",
    title: "Potknięcie w archiwum",
    description:
      "Pracownik potknął się o przewód zasilający podczas transportu segregatorów i doznał skręcenia kostki.",
    category: "Biuro i archiwum",
    priority: "medium",
    status: "resolved",
    reporterName: "Piotr Lewandowski",
    reporterEmail: "piotr.lewandowski@example.com",
    reporterPhone: "+48 555 123 456",
    createdAt: "2025-11-25T12:10:00Z",
    updatedAt: "2025-11-30T15:15:00Z",
    assignedTo: "Katarzyna Dąbrowska",
    notes: "Wyczyściliśmy ciągi komunikacyjne i zabezpieczyliśmy przewody.",
    documentData: {
      pesel: "75081234567",
      nr_dowodu: "DDR445566",
      imie: "Piotr",
      nazwisko: "Lewandowski",
      data_urodzenia: "1975-08-12",
      miejsce_urodzenia: "Gdańsk",
      numer_telefonu: "+48 555 123 456",
      ulica: "Długa",
      nr_domu: "5",
      nr_lokalu: "7",
      miejscowosc: "Gdańsk",
      kod_pocztowy: "80-827",
      data_wypadku: "2025-11-23",
      godzina_wypadku: "09:40",
      miejsce_wypadku: "Archiwum akt pracowniczych",
      planowana_godzina_rozpoczecia_pracy: "08:00",
      planowana_godzina_zakonczenia_pracy: "16:00",
      rodzaj_urazow: "Skręcenie stawu skokowego",
      szczegoly_okolicznosci:
        "Do potknięcia doszło przy ciasnym przejściu. Na podłodze znajdował się przewód przedłużacza.",
      czy_udzielona_pomoc: true,
      miejsce_udzielenia_pomocy: "Lekarz zakładowy",
      organ_postepowania: null,
      czy_wypadek_podczas_uzywania_maszyny: false,
      imie_zglaszajacego: "Piotr",
      nazwisko_zglaszajacego: "Lewandowski",
      nr_telefonu_zglaszajacego: "+48 555 123 456",
    },
  }),
  createDocument({
    documentId: "DOC-005",
    caseNumber: "2025/12/0204",
    title: "Poślizgnięcie w magazynie",
    description:
      "Magazynier poślizgnął się na rozlanej cieczy między regałami wysokiego składowania.",
    category: "Logistyka",
    priority: "medium",
    status: "pending",
    reporterName: "Kamil Król",
    reporterEmail: "kamil.krol@example.com",
    reporterPhone: "+48 600 100 200",
    createdAt: "2025-12-04T09:15:00Z",
    documentData: {
      pesel: "92071506789",
      nr_dowodu: "EER778899",
      imie: "Kamil",
      nazwisko: "Król",
      data_urodzenia: "1992-07-15",
      miejsce_urodzenia: "Radom",
      numer_telefonu: "+48 600 100 200",
      ulica: "Fabryczna",
      nr_domu: "18",
      miejscowosc: "Radom",
      kod_pocztowy: "26-600",
      data_wypadku: "2025-12-03",
      godzina_wypadku: "05:40",
      miejsce_wypadku: "Strefa przyjęć towaru w magazynie",
      planowana_godzina_rozpoczecia_pracy: "06:00",
      planowana_godzina_zakonczenia_pracy: "14:00",
      rodzaj_urazow: "Stłuczenie biodra",
      szczegoly_okolicznosci:
        "Rozlane zostały płyny techniczne z uszkodzonego pojemnika. Strefa nie była oznakowana.",
      czy_udzielona_pomoc: true,
      miejsce_udzielenia_pomocy: "SOR Radom",
      organ_postepowania: null,
      czy_wypadek_podczas_uzywania_maszyny: false,
      imie_zglaszajacego: "Kamil",
      nazwisko_zglaszajacego: "Król",
      nr_telefonu_zglaszajacego: "+48 600 100 200",
    },
  }),
  createDocument({
    documentId: "DOC-006",
    caseNumber: "2025/12/0227",
    title: "Awaria piły taśmowej",
    description:
      "W trakcie prac stolarskich taśma pękła i uderzyła operatora w przedramię, powodując rozcięcie skóry.",
    category: "Obróbka drewna",
    priority: "critical",
    status: "in-progress",
    reporterName: "Paweł Lis",
    reporterEmail: "pawel.lis@example.com",
    reporterPhone: "+48 511 234 678",
    createdAt: "2025-12-04T14:45:00Z",
    assignedTo: "Tomasz Wiśniewski",
    documentData: {
      pesel: "85092145678",
      nr_dowodu: "FFR221133",
      imie: "Paweł",
      nazwisko: "Lis",
      data_urodzenia: "1985-09-21",
      miejsce_urodzenia: "Rzeszów",
      numer_telefonu: "+48 511 234 678",
      ulica: "Kwiatowa",
      nr_domu: "2",
      miejscowosc: "Rzeszów",
      kod_pocztowy: "35-010",
      data_wypadku: "2025-12-04",
      godzina_wypadku: "11:25",
      miejsce_wypadku: "Warsztat stolarski",
      planowana_godzina_rozpoczecia_pracy: "06:00",
      planowana_godzina_zakonczenia_pracy: "14:00",
      rodzaj_urazow: "Rozcięcie przedramienia",
      szczegoly_okolicznosci:
        "Taśma piły zerwała się na skutek zablokowania materiału. Osłona była uniesiona w celu regulacji.",
      czy_udzielona_pomoc: true,
      miejsce_udzielenia_pomocy: "Szpital MSWiA Rzeszów",
      organ_postepowania: "PIP Rzeszów",
      czy_wypadek_podczas_uzywania_maszyny: true,
      opis_maszyn: "Piła taśmowa Stolar 450",
      czy_maszyna_posiada_atest: true,
      czy_maszyna_w_ewidencji: true,
      imie_zglaszajacego: "Paweł",
      nazwisko_zglaszajacego: "Lis",
      nr_telefonu_zglaszajacego: "+48 511 234 678",
    },
  }),
  createDocument({
    documentId: "DOC-007",
    caseNumber: "2025/12/0249",
    title: "Kolizja wózka widłowego",
    description:
      "Operator uderzył w regał wysokiego składowania podczas cofania i doznał urazu barku.",
    category: "Transport wewnętrzny",
    priority: "medium",
    status: "in-progress",
    reporterName: "Adrian Pawlak",
    reporterEmail: "adrian.pawlak@example.com",
    createdAt: "2025-12-04T18:10:00Z",
    updatedAt: "2025-12-05T09:40:00Z",
    assignedTo: "Joanna Grabowska",
    documentData: {
      pesel: "84021011223",
      nr_dowodu: "HTR556644",
      imie: "Adrian",
      nazwisko: "Pawlak",
      data_urodzenia: "1984-02-10",
      miejsce_urodzenia: "Bydgoszcz",
      numer_telefonu: "+48 601 555 777",
      ulica: "Dworcowa",
      nr_domu: "14",
      miejscowosc: "Bydgoszcz",
      kod_pocztowy: "85-009",
      data_wypadku: "2025-12-04",
      godzina_wypadku: "17:45",
      miejsce_wypadku: "Magazyn wysokiego składowania",
      planowana_godzina_rozpoczecia_pracy: "14:00",
      planowana_godzina_zakonczenia_pracy: "22:00",
      rodzaj_urazow: "Stłuczenie barku",
      szczegoly_okolicznosci:
        "Podczas cofania wózkiem widłowym nie zauważono wystającej palety. Doszło do gwałtownego zatrzymania i uderzenia.",
      czy_udzielona_pomoc: true,
      miejsce_udzielenia_pomocy: "Oddział ratunkowy Bydgoszcz",
      organ_postepowania: null,
      czy_wypadek_podczas_uzywania_maszyny: true,
      opis_maszyn: "Wózek widłowy Jungheinrich",
      czy_maszyna_posiada_atest: true,
      czy_maszyna_w_ewidencji: true,
      imie_zglaszajacego: "Adrian",
      nazwisko_zglaszajacego: "Pawlak",
      nr_telefonu_zglaszajacego: "+48 601 555 777",
    },
  }),
  createDocument({
    documentId: "DOC-008",
    caseNumber: "2025/12/0268",
    title: "Przeciążenie kręgosłupa",
    description:
      "Podczas przenoszenia koperty z dokumentami (34 kg) pracownik poczuł ostry ból w odcinku lędźwiowym.",
    category: "Obsługa dokumentów",
    priority: "high",
    status: "pending",
    reporterName: "Renata Sikora",
    reporterEmail: "renata.sikora@example.com",
    reporterPhone: "+48 602 333 411",
    createdAt: "2025-12-05T09:40:00Z",
    documentData: {
      pesel: "81091233445",
      nr_dowodu: "LLO223344",
      imie: "Renata",
      nazwisko: "Sikora",
      data_urodzenia: "1981-09-12",
      miejsce_urodzenia: "Kielce",
      numer_telefonu: "+48 602 333 411",
      ulica: "Lipowa",
      nr_domu: "11",
      nr_lokalu: "3",
      miejscowosc: "Kielce",
      kod_pocztowy: "25-030",
      data_wypadku: "2025-12-04",
      godzina_wypadku: "13:05",
      miejsce_wypadku: "Archiwum zakładowe",
      planowana_godzina_rozpoczecia_pracy: "08:00",
      planowana_godzina_zakonczenia_pracy: "16:00",
      rodzaj_urazow: "Przeciążenie kręgosłupa L5-S1",
      szczegoly_okolicznosci:
        "Przenoszenie pojedynczego pakietu dokumentów przekraczającego dopuszczalną masę przy pracy stojącej.",
      czy_udzielona_pomoc: true,
      miejsce_udzielenia_pomocy: "Poradnia Ortopedyczna",
      organ_postepowania: null,
      czy_wypadek_podczas_uzywania_maszyny: false,
      imie_zglaszajacego: "Renata",
      nazwisko_zglaszajacego: "Sikora",
      nr_telefonu_zglaszajacego: "+48 602 333 411",
    },
  }),
];
