import { Incident } from '@/types/incident';

export const mockIncidents: Incident[] = [
  {
    id: '1',
    caseNumber: '2025/12/0001',
    title: 'Brak wypłaty zasiłku chorobowego',
    description: 'Od trzech tygodni nie otrzymuję zasiłku chorobowego mimo złożenia wszystkich dokumentów.',
    category: 'Zasiłki',
    priority: 'high',
    status: 'pending',
    reporterName: 'Jan Kowalski',
    reporterEmail: 'jan.kowalski@example.com',
    reporterPhone: '+48 123 456 789',
    pesel: '90010112345',
    createdAt: new Date('2025-12-01'),
    updatedAt: new Date('2025-12-01'),
  },
  {
    id: '2',
    caseNumber: '2025/11/0042',
    title: 'Problem z dostępem do konta',
    description: 'Nie mogę zalogować się do systemu PUE ZUS.',
    category: 'Techniczne',
    priority: 'medium',
    status: 'in-progress',
    reporterName: 'Anna Nowak',
    reporterEmail: 'anna.nowak@example.com',
    reporterPhone: '+48 987 654 321',
    pesel: '85050567890',
    createdAt: new Date('2025-11-28'),
    updatedAt: new Date('2025-12-02'),
    assignedTo: 'Tomasz Wiśniewski',
  },
  {
    id: '3',
    caseNumber: '2025/12/0127',
    title: 'Nieprawidłowa wysokość emerytury',
    description: 'Otrzymuję emeryturę w nieprawidłowej wysokości. Proszę o weryfikację.',
    category: 'Emerytury',
    priority: 'high',
    status: 'pending',
    reporterName: 'Maria Zielińska',
    reporterEmail: 'maria.zielinska@example.com',
    pesel: '60032378901',
    createdAt: new Date('2025-12-03'),
    updatedAt: new Date('2025-12-03'),
  },
  {
    id: '4',
    caseNumber: '2025/11/0983',
    title: 'Brak informacji o stażu pracy',
    description: 'W systemie nie widać mojego stażu pracy z lat 1995-2000.',
    category: 'Dokumentacja',
    priority: 'medium',
    status: 'resolved',
    reporterName: 'Piotr Lewandowski',
    reporterEmail: 'piotr.lewandowski@example.com',
    reporterPhone: '+48 555 123 456',
    pesel: '75081234567',
    createdAt: new Date('2025-11-25'),
    updatedAt: new Date('2025-11-30'),
    assignedTo: 'Katarzyna Dąbrowska',
    notes: 'Uzupełniono dane po weryfikacji dokumentów w archiwum.',
  },
  {
    id: '5',
    caseNumber: '2025/12/0204',
    title: 'Błędne naliczenie składek',
    description: 'Otrzymałem informację o zaległościach, mimo regularnego opłacania składek.',
    category: 'Składki',
    priority: 'medium',
    status: 'pending',
    reporterName: 'Kamil Król',
    reporterEmail: 'kamil.krol@example.com',
    reporterPhone: '+48 600 100 200',
    pesel: '92071506789',
    createdAt: new Date('2025-12-04T09:15:00Z'),
    updatedAt: new Date('2025-12-04T09:15:00Z'),
  },
  {
    id: '6',
    caseNumber: '2025/12/0215',
    title: 'Prośba o przyspieszenie decyzji',
    description: 'Złożyłem komplet dokumentów dwa miesiące temu i nadal brak decyzji.',
    category: 'Dokumentacja',
    priority: 'high',
    status: 'pending',
    reporterName: 'Ewelina Bąk',
    reporterEmail: 'ewelina.bak@example.com',
    reporterPhone: '+48 723 900 456',
    pesel: '91092145678',
    createdAt: new Date('2025-12-04T12:20:00Z'),
    updatedAt: new Date('2025-12-04T12:20:00Z'),
  },
  {
    id: '7',
    caseNumber: '2025/12/0227',
    title: 'Problem z wysłaniem e-ZLA',
    description: 'System odrzuca elektroniczne zwolnienie lekarskie.',
    category: 'Techniczne',
    priority: 'critical',
    status: 'in-progress',
    reporterName: 'Dr Paweł Lis',
    reporterEmail: 'pawel.lis@example.com',
    reporterPhone: '+48 511 234 678',
    createdAt: new Date('2025-12-04T14:45:00Z'),
    updatedAt: new Date('2025-12-05T08:05:00Z'),
    assignedTo: 'Tomasz Wiśniewski',
  },
  {
    id: '8',
    caseNumber: '2025/12/0242',
    title: 'Brak historii wpłat na PPK',
    description: 'W panelu nie widzę historii moich wpłat na PPK.',
    category: 'Składki',
    priority: 'medium',
    status: 'pending',
    reporterName: 'Magdalena Olejnik',
    reporterEmail: 'magdalena.olejnik@example.com',
    reporterPhone: '+48 505 777 999',
    createdAt: new Date('2025-12-04T16:30:00Z'),
    updatedAt: new Date('2025-12-04T16:30:00Z'),
  },
  {
    id: '9',
    caseNumber: '2025/12/0249',
    title: 'Potwierdzenie zgłoszenia wypadku',
    description: 'Potrzebuję informacji o statusie zgłoszonego wypadku przy pracy.',
    category: 'Dokumentacja',
    priority: 'medium',
    status: 'in-progress',
    reporterName: 'Adrian Pawlak',
    reporterEmail: 'adrian.pawlak@example.com',
    createdAt: new Date('2025-12-04T18:10:00Z'),
    updatedAt: new Date('2025-12-05T09:40:00Z'),
    assignedTo: 'Joanna Grabowska',
  },
  {
    id: '10',
    caseNumber: '2025/12/0255',
    title: 'Odwołanie od decyzji odmownej',
    description: 'Chciałbym złożyć odwołanie od decyzji odmownej w sprawie zasiłku.',
    category: 'Zasiłki',
    priority: 'medium',
    status: 'pending',
    reporterName: 'Łukasz Sawicki',
    reporterEmail: 'lukasz.sawicki@example.com',
    reporterPhone: '+48 601 888 222',
    pesel: '88102255432',
    createdAt: new Date('2025-12-05T08:25:00Z'),
    updatedAt: new Date('2025-12-05T08:25:00Z'),
  },
  {
    id: '11',
    caseNumber: '2025/12/0268',
    title: 'Brak decyzji o rencie',
    description: 'Minęły trzy miesiące od złożenia wniosku o rentę, brak odpowiedzi.',
    category: 'Zasiłki',
    priority: 'high',
    status: 'pending',
    reporterName: 'Renata Sikora',
    reporterEmail: 'renata.sikora@example.com',
    reporterPhone: '+48 602 333 411',
    createdAt: new Date('2025-12-05T09:40:00Z'),
    updatedAt: new Date('2025-12-05T09:40:00Z'),
  },
  {
    id: '12',
    caseNumber: '2025/12/0273',
    title: 'Korekta danych płatnika',
    description: 'Potrzebuję poprawić dane adresowe płatnika składek.',
    category: 'Dokumentacja',
    priority: 'low',
    status: 'resolved',
    reporterName: 'Karolina Piasecka',
    reporterEmail: 'karolina.piasecka@example.com',
    reporterPhone: '+48 797 654 700',
    createdAt: new Date('2025-12-05T10:55:00Z'),
    updatedAt: new Date('2025-12-05T14:12:00Z'),
    assignedTo: 'Mateusz Kubiak',
    notes: 'Zaktualizowano dane w systemie Płatnik.',
  },
  {
    id: '13',
    caseNumber: '2025/12/0288',
    title: 'Brak potwierdzenia wysyłki dokumentów',
    description: 'Po wgraniu dokumentów nie otrzymałem potwierdzenia ich przyjęcia.',
    category: 'Techniczne',
    priority: 'medium',
    status: 'in-progress',
    reporterName: 'Natalia Kalinowska',
    reporterEmail: 'natalia.kalinowska@example.com',
    createdAt: new Date('2025-12-05T12:20:00Z'),
    updatedAt: new Date('2025-12-05T16:45:00Z'),
    assignedTo: 'Tomasz Wiśniewski',
  },
  {
    id: '14',
    caseNumber: '2025/12/0299',
    title: 'Rozbieżność danych o zatrudnieniu',
    description: 'Moje świadectwa pracy nie zostały prawidłowo przeniesione do systemu.',
    category: 'Dokumentacja',
    priority: 'high',
    status: 'pending',
    reporterName: 'Grzegorz Czarnecki',
    reporterEmail: 'grzegorz.czarnecki@example.com',
    reporterPhone: '+48 510 210 310',
    createdAt: new Date('2025-12-05T14:10:00Z'),
    updatedAt: new Date('2025-12-05T14:10:00Z'),
  },
  {
    id: '15',
    caseNumber: '2025/12/0306',
    title: 'Powiadomienie o błędzie systemu',
    description: 'Podczas logowania otrzymuję komunikat o błędzie serwera.',
    category: 'Techniczne',
    priority: 'medium',
    status: 'resolved',
    reporterName: 'Oskar Baran',
    reporterEmail: 'oskar.baran@example.com',
    createdAt: new Date('2025-12-05T16:30:00Z'),
    updatedAt: new Date('2025-12-06T08:00:00Z'),
    assignedTo: 'Sylwia Michalska',
    notes: 'Zrestartowano zasoby i poinformowano użytkownika.',
  },
  {
    id: '16',
    caseNumber: '2025/12/0311',
    title: 'Zapytanie o wysokość składek zdrowotnych',
    description: 'Potrzebuję wyliczenia składek zdrowotnych za ostatni kwartał.',
    category: 'Składki',
    priority: 'low',
    status: 'pending',
    reporterName: 'Patrycja Chmiel',
    reporterEmail: 'patrycja.chmiel@example.com',
    reporterPhone: '+48 601 440 770',
    createdAt: new Date('2025-12-05T17:45:00Z'),
    updatedAt: new Date('2025-12-05T17:45:00Z'),
  },
  {
    id: '17',
    caseNumber: '2025/12/0318',
    title: 'Zgłoszenie błędu w danych firmy',
    description: 'W systemie PUE wyświetla się nieaktualny adres mojej firmy.',
    category: 'Dokumentacja',
    priority: 'medium',
    status: 'in-progress',
    reporterName: 'Marek Dudziak',
    reporterEmail: 'marek.dudziak@example.com',
    createdAt: new Date('2025-12-06T08:10:00Z'),
    updatedAt: new Date('2025-12-06T10:20:00Z'),
    assignedTo: 'Mateusz Kubiak',
  },
  {
    id: '18',
    caseNumber: '2025/12/0325',
    title: 'Prośba o interpretację przepisów',
    description: 'Czy mogę łączyć zasiłek rehabilitacyjny z prowadzeniem działalności?',
    category: 'Inne',
    priority: 'low',
    status: 'pending',
    reporterName: 'Agnieszka Nowicka',
    reporterEmail: 'agnieszka.nowicka@example.com',
    createdAt: new Date('2025-12-06T09:30:00Z'),
    updatedAt: new Date('2025-12-06T09:30:00Z'),
  },
  {
    id: '19',
    caseNumber: '2025/12/0334',
    title: 'Brak potwierdzenia zgłoszenia działalności',
    description: 'Zgłosiłem nową działalność, ale nie ma potwierdzenia w systemie.',
    category: 'Dokumentacja',
    priority: 'medium',
    status: 'pending',
    reporterName: 'Sebastian Wrona',
    reporterEmail: 'sebastian.wrona@example.com',
    reporterPhone: '+48 723 333 555',
    createdAt: new Date('2025-12-06T10:45:00Z'),
    updatedAt: new Date('2025-12-06T10:45:00Z'),
  },
  {
    id: '20',
    caseNumber: '2025/12/0340',
    title: 'Zapytanie o świadczenie rehabilitacyjne',
    description: 'Chciałabym uzyskać informacje o dokumentach potrzebnych do świadczenia rehabilitacyjnego.',
    category: 'Zasiłki',
    priority: 'low',
    status: 'pending',
    reporterName: 'Jolanta Marciniak',
    reporterEmail: 'jolanta.marciniak@example.com',
    createdAt: new Date('2025-12-06T11:55:00Z'),
    updatedAt: new Date('2025-12-06T11:55:00Z'),
  },
  {
    id: '21',
    caseNumber: '2025/12/0347',
    title: 'Rejestracja nowego pracownika',
    description: 'System zgłasza błąd podczas rejestracji nowego pracownika.',
    category: 'Techniczne',
    priority: 'high',
    status: 'in-progress',
    reporterName: 'Przedsiębiorstwo Alfa',
    reporterEmail: 'hr@alfa.example.com',
    reporterPhone: '+48 800 555 010',
    createdAt: new Date('2025-12-06T13:05:00Z'),
    updatedAt: new Date('2025-12-06T13:45:00Z'),
    assignedTo: 'Sylwia Michalska',
  },
  {
    id: '22',
    caseNumber: '2025/12/0351',
    title: 'Zgłoszenie błędu w zawieszeniu działalności',
    description: 'Po zgłoszeniu zawieszenia działalności nadal naliczane są składki.',
    category: 'Składki',
    priority: 'high',
    status: 'pending',
    reporterName: 'Dorota Urban',
    reporterEmail: 'dorota.urban@example.com',
    reporterPhone: '+48 512 909 808',
    createdAt: new Date('2025-12-06T14:20:00Z'),
    updatedAt: new Date('2025-12-06T14:20:00Z'),
  },
  {
    id: '23',
    caseNumber: '2025/12/0360',
    title: 'Brak możliwości pobrania zaświadczenia A1',
    description: 'Po zalogowaniu brak dostępu do generowania zaświadczeń A1.',
    category: 'Techniczne',
    priority: 'critical',
    status: 'in-progress',
    reporterName: 'Firma Beta',
    reporterEmail: 'biuro@beta.example.com',
    createdAt: new Date('2025-12-06T15:30:00Z'),
    updatedAt: new Date('2025-12-06T16:10:00Z'),
    assignedTo: 'Joanna Grabowska',
  },
  {
    id: '24',
    caseNumber: '2025/12/0368',
    title: 'Prośba o ponowne wysłanie decyzji',
    description: 'Nie dotarła do mnie decyzja w sprawie wniosku o świadczenie.',
    category: 'Dokumentacja',
    priority: 'medium',
    status: 'pending',
    reporterName: 'Zofia Wysocka',
    reporterEmail: 'zofia.wysocka@example.com',
    createdAt: new Date('2025-12-06T16:40:00Z'),
    updatedAt: new Date('2025-12-06T16:40:00Z'),
  },
  {
    id: '25',
    caseNumber: '2025/12/0374',
    title: 'Wyjaśnienie różnicy w liczbie dni chorobowych',
    description: 'System pokazuje inną liczbę dni chorobowych niż dokumenty papierowe.',
    category: 'Dokumentacja',
    priority: 'medium',
    status: 'pending',
    reporterName: 'Katarzyna Kurek',
    reporterEmail: 'katarzyna.kurek@example.com',
    createdAt: new Date('2025-12-06T17:15:00Z'),
    updatedAt: new Date('2025-12-06T17:15:00Z'),
  },
];
