import { Incident } from '@/types/incident';

export const mockIncidents: Incident[] = [
  {
    id: '1',
    title: 'Brak wypłaty zasiłku chorobowego',
    description: 'Od trzech tygodni nie otrzymuję zasiłku chorobowego mimo złożenia wszystkich dokumentów.',
    category: 'Zasiłki',
    priority: 'high',
    status: 'pending',
    reporterName: 'Jan Kowalski',
    reporterEmail: 'jan.kowalski@example.com',
    reporterPhone: '+48 123 456 789',
    pesel: '90010112345',
    createdAt: new Date('2025-12-01'),
    updatedAt: new Date('2025-12-01'),
  },
  {
    id: '2',
    title: 'Problem z dostępem do konta',
    description: 'Nie mogę zalogować się do systemu PUE ZUS.',
    category: 'Techniczne',
    priority: 'medium',
    status: 'in-progress',
    reporterName: 'Anna Nowak',
    reporterEmail: 'anna.nowak@example.com',
    reporterPhone: '+48 987 654 321',
    pesel: '85050567890',
    createdAt: new Date('2025-11-28'),
    updatedAt: new Date('2025-12-02'),
    assignedTo: 'Tomasz Wiśniewski',
  },
  {
    id: '3',
    title: 'Nieprawidłowa wysokość emerytury',
    description: 'Otrzymuję emeryturę w nieprawidłowej wysokości. Proszę o weryfikację.',
    category: 'Emerytury',
    priority: 'high',
    status: 'pending',
    reporterName: 'Maria Zielińska',
    reporterEmail: 'maria.zielinska@example.com',
    pesel: '60032378901',
    createdAt: new Date('2025-12-03'),
    updatedAt: new Date('2025-12-03'),
  },
  {
    id: '4',
    title: 'Brak informacji o stażu pracy',
    description: 'W systemie nie widać mojego stażu pracy z lat 1995-2000.',
    category: 'Dokumentacja',
    priority: 'medium',
    status: 'resolved',
    reporterName: 'Piotr Lewandowski',
    reporterEmail: 'piotr.lewandowski@example.com',
    reporterPhone: '+48 555 123 456',
    pesel: '75081234567',
    createdAt: new Date('2025-11-25'),
    updatedAt: new Date('2025-11-30'),
    assignedTo: 'Katarzyna Dąbrowska',
    notes: 'Uzupełniono dane po weryfikacji dokumentów w archiwum.',
  },
];
